### ISSUE TITLE
Every page except About loads blank in the web interface

### ISSUE THREAD

**Issue by smiller171** [ansible/galaxy-issues#101]
I can't get explore, browse, my roles, or my imports to load in Galaxy 2.0

This appears to be related to ad/privacy blockers. If analytics are blocked, several pages fail to load in Galaxy.

**Comment by chouseknecht** [comment]
I'm not seeing this with Chrome or Firefox. https://galaxy-qa.ansible.com is fully functional, as far as I can tell. Wondering if things were down/broken on the day this issue was opened. 

Are you still experiencing this?  If so, can you provide more details such as: browser, browser version, platform, etc.  Have you cleared the browse cache? 

Also, are you authenticating with Galaxy? And if so, by which means (i.e. password, GitHub, Twitter, etc.)?

Thanks,

Chris

**Comment by smiller171** [comment]
Appears to be working just fine for me now.

**Comment by bryandowning** [comment]
I'm experiencing similar behavior with https://galaxy.ansible.com/. I'm seeing slow response times. Most of the time I try to load a page, I see in Chrome dev tools several front-end assets don't load because of network timeouts (the assets that fail to load seem to change from page to page).

This is the console output when I load the Browse Roles page (I'm not authenticated).

```
list:38 GET https://galaxy.ansible.com/static/vendorjs/select2.js net::ERR_TIMED_OUT
list:39 GET https://galaxy.ansible.com/static/vendorjs/underscore-min.js net::ERR_TIMED_OUT
list:45 GET https://galaxy.ansible.com/static/dist/galaxy.listApp.min.js net::ERR_TIMED_OUT
angular.js:36 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.2.28/$injector/modulerr?p0=listApp&p1=Error%3…3A%2F%2Fgalaxy.ansible.com%2Fstatic%2Fvendorjs%2Fangular.min.js%3A18%3A387)
```

Note: I'm seeing this in latest Chrome and Firefox on OS X.

I'm also experiencing connectivity issues when trying to install roles via CLI. I'm following the instructions at https://github.com/roots/roots-example-project.com, but when I tried to install the Ansible roles last night, I saw this several times:

```
bryan:roots-example-project.com bryandowning$ cd trellis && ansible-galaxy install -r requirements.yml
- the API server (galaxy.ansible.com) is not responding, please try again later.
```

Then, I tried again today, and saw this several times:

```
bryan:trellis bryandowning$ ansible-galaxy install -r requirements.yml
- downloading role 'project_deploy_module', owned by f500
- sorry, f500.project_deploy_module was not found on galaxy.ansible.com.
- you can use --ignore-errors to skip failed roles.
```

Then on the fourth try:

```
bryan:trellis bryandowning$ ansible-galaxy install -r requirements.yml
- downloading role 'project_deploy_module', owned by f500
- downloading role from https://github.com/f500/ansible-project_deploy_module/archive/v1.0.3.tar.gz
- extracting f500.project_deploy_module to vendor/roles/f500.project_deploy_module
- f500.project_deploy_module was installed successfully
- the API server (galaxy.ansible.com) is not responding, please try again later.
```

Feels like the server is under extreme load, like a DDoS attack.

**Comment by bryandowning** [comment]
I should also mention that https://galaxy-qa.ansible.com seems to be working flawlessly for me.

**Comment by chouseknecht** [comment]
Galaxy is hosted on Linode. Unfortunately they've been undergoing DoS attacks over the last week: http://tech.slashdot.org/story/16/01/01/2321211/linode-under-ddos-since-christmas

**Comment by smiller171** [comment]
Why is Galaxy hosted on a service small enough that the entire host can be affected by a DoS attack?

**Comment by gregdek** [comment]
Because until relatively recently, we were a scrappy startup that could fit all of our employees into a clown car. Now that we're starting to integrate with our new friends at Red Hat and have more resources at our disposal, we will be migrating to a more robust provider.

**Comment by smiller171** [comment]
I've never understood the price argument when it comes to picking a cloud host. The price is pretty similar to AWS t2 instances it looks like. Glad to hear you'll be moving to something more robust.

**Comment by bryandowning** [comment]
Thanks a lot for the info @chouseknecht and @gregdek!

**Comment by smiller171** [comment]
Update: I'm still experiencing issues with Galaxy 2.0 in prod. It works in an incognito tab, but even having cleared cache and cookies it's not loading properly in a regular tab. Going to try disabling extensions one at a time to see if there is a conflict.

**Comment by smiller171** [comment]
I found the culprit:

I'm using Ublock, and it's blocking analytics by default. For some reason if analytics are blocked, several pages (browse roles, my roles, perhaps others) fail to load.

long story short: disable ad blockers or turn off privacy filters to make the new Galaxy work.

**Comment by chouseknecht** [comment]
Ah. So we probably made some assumptions in JS that Google Analytics will always be available. We'll take a look and see if we can make things happy even when GA is not loaded or blocked.

**Comment by smiller171** [comment]
@chouseknecht It looks like there is another analytics engine being loaded in addition to Google. I don't know which is causing the issue.

**Comment by chouseknecht** [comment]
We also load hubspot, but I don't think it's causing the issue. We'll get to the bottom of it.

**Comment by groggemans** [comment]
This is the console output when allowing `google-analytics.com`, `hs-analytics.net` and `hubspot.com`.

```
GET https://galaxy.ansible.com/static/vendorjs/angulartics-google-analytics.min.js net::ERR_BLOCKED_BY_CLIENT

angular.js:38 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=roleAddApp&p1=Error…
3A%2F%2Fgalaxy.ansible.com%2Fstatic%2Fvendorjs%2Fangular.min.js%3A19%3A463)(anonymous function) @ angular.js:38(anonymous function) @ angular.js:4413m @ angular.js:336h @ angular.js:4374fb @ angular.js:4299d @ angular.js:1657zc @ angular.js:1678Zd @ angular.js:1572(anonymous function) @ angular.js:28899j @ jquery.js:3148k.fireWith @ jquery.js:3260m.extend.ready @ jquery.js:3472J @ jquery.js:3503
```

If I allow everything from `galaxy.ansible.com` and block those analytics domains everything works fine.

**Comment by chouseknecht** [comment]
Script files now load. Tested with uBlock Origin. Requests to GA, Hubspot and Pendo are blocked, but the application seems to function OK.

**Comment by groggemans** [comment]
Just tested on galaxy-qa and it also works here, great work!
(uBlock Origin)
