### ISSUE TITLE
Add Solaris platform to ansible-galaxy

### ISSUE THREAD

**Issue by liquidat** [ansible/galaxy-issues#102]
Currently Ansible Galaxy only supports various Linux distributions, variants of BSD, SmartOS, Windows and a GenericUNIX, whatever that is. Solaris is missing here, although Ansible properly runs on Solaris out of the box, and the OS family "Solaris" is correctly identified by the setup plugin. The same is true for ansible_distribution (also "Solaris") and ansible_distribution_version.

Thus please add Solaris as a platform family to Ansible Galaxy. In best case this would cover Solaris 10 and 11 since both are pretty different (new package format, etc.).
- name: Solaris versions:
  - all
  - 10
  - 11.0
  - 11.1
  - 11.2
  - 11.3

**Comment by chouseknecht** [comment]
Solaris is now a platform.
