### ISSUE TITLE
Galaxy site footer is not consistent

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-issues#104]
Noticing on Browse Roles the 'BETA' label still appears. And on Author pages the 2.0.0 is missing.

**Comment by jakemcdermott** [comment]
There's some additional blank / non-rendered version numbers on the following pages:
- /authors
- /accounts/email/
- /accounts/social/connections
- The 404 not found page

<img width="404" alt="screen shot 2016-02-16 at 12 01 17 pm" src="https://cloud.githubusercontent.com/assets/9753817/13083953/3defc560-d4a5-11e5-8e3b-14637878e953.png">

**Comment by chouseknecht** [comment]
This is fixed now. The version number is now available to all templates.
