### ISSUE TITLE
Ad-blocker blocks vital content

### ISSUE THREAD

**Issue by groggemans** [ansible/galaxy-issues#106]
With an active ad-blocker, a lot of the functionality is not working in galaxy 2.

It would be nice if there was a message that tells people to disable there ad-blockers on galaxy. (not needed anyway)

_(I'm using uBlock Origin)_

**Comment by chouseknecht** [comment]
This is a duplicate of https://github.com/ansible/galaxy-issues/issues/101

**Comment by groggemans** [comment]
Oops, missed that one, sorry!
