### ISSUE TITLE
'My Roles' not displaying all roles

### ISSUE THREAD

**Issue by kbrebanov** [ansible/galaxy-issues#107]
Look like the 'My Roles' page only lists the first 100 repositories from GitHub.

**Comment by chouseknecht** [comment]
Started tracking this down. The issue is in pagination of the RepositoryList view. It's not a front-end problem.

**Comment by chouseknecht** [comment]
Fixed. There was actually a setting for max page size. Bumped it from 100 to 1000. This is fixed in production.
