### ISSUE TITLE
Role listed multiple (2) times

### ISSUE THREAD

**Issue by groggemans** [ansible/galaxy-issues#109]
Can't seem to recreate the issue but I was working on my roles and one of them was suddenly listed twice under my roles. Disabling/enabling didn't solve the issue, renewing the list did.

**Comment by MiLk** [comment]
I had a same issue soon after the release of the new version.
After doing a few refresh and imports, it seems to be ok.
I had to disable/enable a few roles.

**Comment by chouseknecht** [comment]
Fixed pushed to galaxy-qa.ansible.com. Duplicate of issue 117.
