### ISSUE TITLE
Support shared/linked company accounts 

### ISSUE THREAD

**Issue by gregdek** [ansible/galaxy-issues#11]
Need more info here though.

**Comment by srgvg** [comment]
:+1: see also my comment on #64

**Comment by MiLk** [comment]
That would be a great feature.
Connecting with your personal GH account, and having access to your organization on galaxy, which will contain roles.
So that several people can access the organization's role with their personal accounts.

**Comment by 0x46616c6b** [comment]
+1

**Comment by martinb3** [comment]
+1, we need this and due to the January Github requirements, we're basically stuck until we have this. Thanks!

**Comment by gregdek** [comment]
This already works. If you are publicly listed as a "member" of an organization, you have the option to push under the namespace of that organization.

**Comment by martinb3** [comment]
Aha! Being listed publicly was the trick. I'd highly recommend putting that on the page that lists roles.

It currently says:

> If you don't see all of your roles, review and add your authorized organizations.

I couldn't find anything about public membership. That's a key point.
