### ISSUE TITLE
Reimport fails silently w/o informing the user

### ISSUE THREAD

**Issue by exploide** [ansible/galaxy-issues#111]
When reimporting some roles within the "My Roles" page by clicking the "Re-import Role" button, there is no feedback if the reimport was successful. If an error happened, one can only notice by manually visiting each "View Role Import Details" page.

It would be great if Galaxy could provide instant feedback if the reimport was successful.

**Comment by chouseknecht** [comment]
Good idea. Adding this to the list for next release.

**Comment by jeqo** [comment]
Hi, I have the same issue, try to re-import a role and when I refresh the page, role is not imported, and there are no log about what goes wrong.
+1 for instant feedback.

**Comment by chouseknecht** [comment]
Adding an indicator that shows red or green based on status of last import. Will still need to click on the View Import Details button to see the import log and troubleshoot.
