### ISSUE TITLE
Add  FreeBSD 9.1, 9.3, 10.0, 10.1 and 10.2

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-issues#112]
Loïc BLOT@Unix_XP
@ansible can you add FreeBSD 9.1, 9.3, 10.0, 10.1 and 10.2 to your galaxy ? Thanks :) https://pbs.twimg.com/media/CaC_me6WcAA--aB.png (7KB)

**Comment by nerzhul** [comment]
Thanks for opening the issue :)

**Comment by chouseknecht** [comment]
Added

**Comment by nerzhul** [comment]
Thanks
