### ISSUE TITLE
link to "Travis CI" not loading

### ISSUE THREAD

**Issue by shibinmk** [ansible/galaxy-issues#114]
In the Galaxy page https://galaxy.ansible.com/intro#travis , A link to 'Travis CI' at "Try it" description area is pointing to wrong address "http://travic-ci.org/". I believe it should be https://travis-ci.org/.

**Comment by jakemcdermott** [comment]
Two more:

1.

<img width="1366" alt="broken_link_1" src="https://cloud.githubusercontent.com/assets/9753817/13083677/11e5f60c-d4a4-11e5-8750-8331e52acb7b.png">

2.
<img width="1386" alt="broken_link_2" src="https://cloud.githubusercontent.com/assets/9753817/13083679/166e1d9e-d4a4-11e5-8e29-39b97279a613.png">

The second link isn't technically broken but it doesn't actually link to the travis documentation.

**Comment by chouseknecht** [comment]
Fixed.
