### ISSUE TITLE
An error occurred while saving the role: value too long for type character varying(256)

### ISSUE THREAD

**Issue by felnne** [ansible/galaxy-issues#115]
Hi,

On importing this role: https://github.com/bas-ansible-roles-collection/system-hostname

I get this 'error':

```
Starting import 950: role_name=system-hostname repo=bas-ansible-roles-collection/system-hostname ref=
Retrieving Github repo bas-ansible-roles-collection/system-hostname
Accessing branch: master
Parsing and validating meta/main.yml
Parsing galaxy_tags
Parsing platforms
Adding dependencies
Parsing and validating README.md
Adding repo tags as role versions
Import completed
Status SUCCESS : warnings=0 errors=0
An error occurred while saving the role: value too long for type character varying(256)
```

I don't know what information is 'too long' , I assume it isn't the role name, since that's only 45 charaters long.

I've tried re-importing the role (import 951) and got the same error.

I depend on this role in other roles and currently can't update them because this role can't be found so this has effectively broken all my other roles.

Could someone advise what this is referring to?

Thanks,
Felix.

**Comment by felnne** [comment]
This appears to be affecting all my roles, as import '952' has the same issue but for a different repository.

**Comment by chouseknecht** [comment]
I'm looking at it now.  Will let you know what I find.

**Comment by chouseknecht** [comment]
Error in the import process when commit message exceeds 256 chars. Added truncation for role.commit and import_task.commit. Added error checking to test length of all Char fields going forward. This will at least provide the name of the field should it come up again.

**Comment by felnne** [comment]
Hi @chouseknecht,

Thanks for fixing that so quickly. I've managed to successfully import all the roles which failed using galaxy-qa.

As a workaround I am trying use galaxy-qa to get the ansible-galaxy command to work.

However when I try:

``` shell
$ ansible-galaxy install --server https://galaxy-qa.ansible.com bas-ansible-roles-collection.system-hostname
```

I get back this error:

```
- the API server (https://galaxy-qa.ansible.com) is not responding, please try again later.
```

The galaxy-qa website seems to working ok so not sure if the API is different to the website, or if there's an issue on my end. I'm using Ansible 1.9.4.

Can you confirm if that command should have worked or am I misunderstanding how that works.

Thanks,
Felix

**Comment by chouseknecht** [comment]
This may depend on the version of ansible you are using. I ran the above command and it works fine for me:

```
$ ansible-galaxy install --server https://galaxy-qa.ansible.com bas-ansible-roles-collection.system-hostname
- downloading role 'system-hostname', owned by bas-ansible-roles-collection
- downloading role from https://github.com/bas-ansible-roles-collection/system-hostname/archive/v0.2.1.tar.gz
- extracting bas-ansible-roles-collection.system-hostname to /Users/chouseknecht/projects/roles/bas-ansible-roles-collection.system-hostname
- bas-ansible-roles-collection.system-hostname was installed successfully
```

In older versions of ansible I believe you did not provide the protocol in the server address. So try:

```
ansible-galaxy install --server galaxy-qa.ansible.com bas-ansible-roles-collection.system-hostname
```

**Comment by felnne** [comment]
Hi, this issue seems to be fixed on the production Galaxy now (i've successfully imported a number of new roles which previously failed).
