### ISSUE TITLE
Add title to role pages

### ISSUE THREAD

**Issue by gregdek** [ansible/galaxy-issues#12]
https://twitter.com/fbcoelho/status/623937457743110145

"Can you add the role title for the role pages in Galaxy? It's kinda hard to find a previous role right now "

**Comment by gregdek** [comment]
So the issue is that the title in the browser, for browser history purposes, is always just the "Ansible Galaxy" title tag.

**Comment by chouseknecht** [comment]
Fixed.  On role detail page the page title is now dynamically set to 'Galaxy - username.role_name'.  On the user detail page it gets set to 'Galaxy - username'.

![better titles](https://cloud.githubusercontent.com/assets/1282865/10103236/d20bf6f2-6370-11e5-81bb-4b774dad04ff.png)

**Comment by gregdek** [comment]
Confirmed that this now works as expected.

**Comment by gregdek** [comment]
Shipped!
