### ISSUE TITLE
Role unavailable with my last changes

### ISSUE THREAD

**Issue by evrardjp** [ansible/galaxy-issues#121]
Hello, 

I wanted to upload a new version of my https://github.com/evrardjp/ansible-keepalived role with the web interface but the import was in "waiting to start".

I've tried to disable and reenable the role, which doesn't solve the issue. Worse, it even makes the role unavailable, and lost my stats!

Is it possible to fix this?

**Comment by evrardjp** [comment]
Hello, 

I also tried to remove the role, re-import it with another name (ansible-keepalived instead of keepalived), but I hit the same issue: nothing going on.

**Comment by chouseknecht** [comment]
The task runner got hung up and imports stopped working. Imports are working again. There is a backlog of imports it has to work through, so your import may not start right away. Just leave it in the queue. 

And yes, if you turn off the role, it deletes it per the instructions at the top of the page.

**Comment by chouseknecht** [comment]
I am not seeing your role in the import logs, and it still shows a status of 'pending'.  Can you please go to EVRARDJP-> My Imports and click the Re-Import button on the top-right corner of the page, and let's see if it will import now.

**Comment by chouseknecht** [comment]
On My Roles page it needs to be made more clear to the user that turning off a role will delete it, and the download count will be lost.

**Comment by nrb** [comment]
@chouseknecht Thanks for the help! I'm curious if the feature request I put in for ansible's role requirement files to allow fall back URLs will get any traction, but also realize I may be talking to the wrong team here.

**Comment by chouseknecht** [comment]
On the Galaxy site side of things, downloading roles is generally reliable with the exception of brief maintenance windows. Even if the import process goes down, roles can still be downloaded. We also moved to a new cloud provider, which eliminates the network interruptions like we saw back in November and December.

The feature request certainly seems reasonable, but for the Galaxy site right now the priority is quashing bugs and stabilizing the import process.

**Comment by evrardjp** [comment]
I've re-imported the role successfully.

Thanks for your help.

**Comment by chouseknecht** [comment]
I think the work to do here is: 

New Feature:  On My Roles page it needs to be made more clear to the user that turning off a role will delete it, and the download count will be lost.

More work needs to be done to stabilize the task runner. [See issue 113](https://github.com/ansible/galaxy-issues/issues/113).
