### ISSUE TITLE
Edit role name changes should be reflected on import roles page

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/galaxy-issues#122]
On the import roles page (/roleadd#/), there should probably be some indication that you've changed the galaxy role name of an imported github role. 

Some example user stories  / test cases: 

1.

As a user I want to:

Click on My Roles from the header menu
View the My Roles Page
Click the role settings gearbox icon next to one of my roles
Change the role name for my selected role
Click the save button
Verify that my changes have taken place without going to another page or re-opening the settings menu for my roles. 

2.

As a user I want to:

Click on My Roles from the header menu
View the My Roles Page
Verify which of my imported roles I've remapped names for in the past without having to open the 
settings menu for each role.

**Comment by chouseknecht** [comment]
Added tooltip to the GitHub repo name. When the role is enabled the repo name is a link to the role. Added a tooltip to the link. The tooltip is only visible when the repo is enabled. The tooltip shows the full role name. If role name is altered, the tooltip changes. Hover over the repo name to reveal the tooltip.
