### ISSUE TITLE
Edit role name changes shouldn't result in broken links

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/galaxy-issues#123]
- Click on My Roles from the header menu
- Click the role settings gearbox icon next to a role
- Change the role name to something with special characters / corrupted text
- Click the save button

Links to this role from the Explore, Browse Roles, and My Roles pages are now broken. 

![screenshot_01](https://cloud.githubusercontent.com/assets/9753817/13089780/4f34259e-d4c0-11e5-99f0-6ddfd4a1e7c8.png)

![screenshot_02](https://cloud.githubusercontent.com/assets/9753817/13089792/558e00c2-d4c0-11e5-9775-3903b3611c67.png)

**Comment by goldyfruit** [comment]
Hi guys,

Same for me, I just added a role but I got a 404.

Thanks.

**Comment by chouseknecht** [comment]
The point of this issue is to disallow names not matching /^[A-Za-z0-9_-]+$/.  Added form validation to catch invalid input and raise an error.

@goldyfruit if you are experiencing an error not related to this, please open a new issue.
