### ISSUE TITLE
Users shouldn't be able to bypass pagination limits by modifying the url

### ISSUE THREAD

**Issue by jakemcdermott** [ansible/galaxy-issues#124]
- Click on My Roles from the header menu
- Change the 'page_size' query parameter in the URL to something big

The application is now unresponsive / hard to use

![galaxy_page_size](https://cloud.githubusercontent.com/assets/9753817/13090037/8f65b1e0-d4c1-11e5-9ec9-f149f368125c.png)

**Comment by chouseknecht** [comment]
Actually, I think this is not a bug, or at least one that's not critical. The parameter in the URL is a legit parameter. A user could put a value of say '16', which is not one of the selections in the page size drop-down. If they do, the page shows 16, but the page size drop-down goes blank, and the paging widget works just fine. I think this is OK.

But if someones futz's with page size and puts in a really big number and things are sort of broken... I don't think is a thing.

**Comment by chouseknecht** [comment]
I somewhat fixed this. Despite what the user sets the page_size value to, the max page_size value sent to the API is now 100. I can't find an easy way to limit the page size on the API. May revisit in the future.
