### ISSUE TITLE
Importing roles stuck in "Waiting to start"

### ISSUE THREAD

**Issue by rogerscuall** [ansible/galaxy-issues#125]
I'm trying to import a new role from github and when I go to details and I click re-import roles I only have this back.
<img width="780" alt="screen shot 2016-02-16 at 6 24 40 pm" src="https://cloud.githubusercontent.com/assets/5758351/13094718/9c19cb06-d4da-11e5-8a91-48e585cb153d.png">
Thanks.

**Comment by nrb** [comment]
Looks related to #121

**Comment by rogerscuall** [comment]
Seems like this was resolved, is now working no change needed.

**Comment by nrb** [comment]
Yep, looks like https://github.com/ansible/galaxy-issues/issues/121#issuecomment-184966737 fixed it

**Comment by chouseknecht** [comment]
Closing this as the root cause is being tracked in [issue 113](https://github.com/ansible/galaxy-issues/issues/113)
