### ISSUE TITLE
Deleting roles does not delete roles

### ISSUE THREAD

**Issue by emonty** [ansible/galaxy-issues#127]
I went to https://galaxy.ansible.com/roleadd#/ and un-checked the emonty/puppet role. But https://galaxy.ansible.com/emonty/puppet/ is still in existence.

**Comment by chouseknecht** [comment]
So there now seems to be no emonty. https://galaxy.ansible.com/emonty/ returns a 404 page not found, which means that the one role was removed.

I'm not sure what was unique about the role that made it seem to not delete at first. The general 'delete a role' function works, as I can delete roles that belong to me. Did your puppet role happen to use an alternate name?

**Comment by chouseknecht** [comment]
Seeing the error you're experiencing while attempting to connect via Github. It seems to be related to accessing your email address from the GitHub API. Wondering if it is a scope issue that's not being surfaced. Galaxy asks for a scope of user:email from GitHub. Specifically it is attempting to access https://api.github.com/user/emails. Either it can't access it, or the token we have is no longer valid.

**Comment by chouseknecht** [comment]
I deleted the token we have, in hopes that GitHub will generate a new one and that will fix the issue. Also, check in your GitHub settings that Galaxy is authorized to access your email address.

**Comment by emonty** [comment]
On 02/17/2016 02:35 PM, Chris Houseknecht wrote:

> I deleted the token we have, in hopes that GitHub will generate a new
> one and that will fix the issue. Also, check in your GitHub settings
> that Galaxy is authorized to access your email address.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/galaxy-issues/issues/127#issuecomment-185231043.

I seem to be in now!

**Comment by chouseknecht** [comment]
Awesome!  Apologies for all the difficulty.

**Comment by chouseknecht** [comment]
Closing this issue and tracking the expired token / email issue [here](https://github.com/ansible/galaxy-issues/issues/128).

**Comment by mat-green** [comment]
- I went to https://galaxy.ansible.com/roleadd#/ and un-checked a role.
- Confirmation box appears.
- Click on `Delete` button and nothing happens.
- Click on `Cancel` to remove confirmation box but the role stays checked.
