### ISSUE TITLE
When Travis notifies on a new tag, tag is not imported into Galaxy

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy-issues#129]
I'm not sure if I'm missing something simple here, but it seems that the primary time I want Galaxy to be notified and pick up new changes to my role repositories is after a new tag is pushed up.

I've hit this problem on all my roles, but finally decided to post this question/possible bug report after hitting it on my Node.js role: https://galaxy.ansible.com/geerlingguy/nodejs/

I was monitoring the Galaxy import page for that role (https://galaxy.ansible.com/imports#/?github_user=geerlingguy&github_repo=ansible-role-nodejs), and when I pushed or merged commits to master, after the Travis build completed, Galaxy picked up the changes and re-imported the role automatically.

For tag builds (e.g. 2.1.0: https://travis-ci.org/geerlingguy/ansible-role-nodejs/builds/110549451), it seems a notification is either not sent, or not received by Galaxy. After half an hour of not seeing Galaxy re-import, I click the import button manually.

Scenario 1:
1. I push/merge a commit to role's `master` branch.
2. Travis runs a build.
3. Travis posts request to Galaxy notification after success.
4. Galaxy indicates a successful role import.

Scenario 2:
1. I push a new _tag_ to role's master branch.
2. Travis runs a build.
3. Travis posts request to Galaxy notification after success.
4. Galaxy never runs an automatic role import.

In Scenario 2, I can either go in and do a manual role import to get things up to date, or wait until the next Travis build completes; it seems that non-tag builds notify Galaxy properly. Am I just missing a setting here?

**Comment by chouseknecht** [comment]
It looks like travis is sending a branch value in the notification payload that does not match the branch we have on the role. I pushed a tag to a test repo, received a notification, and got this as the message for why an import did not fire: "Skipping role 6418 - github_branch  does not match requested branch."

The branch in the Travis notification is the tag. It seems we should just fire an import each time we receive a notification and not try to decipher which branch it maps to.

**Comment by chouseknecht** [comment]
Done. This is working now in our QA environment. It will get pushed to production on Friday.

**Comment by geerlingguy** [comment]
@chouseknecht thanks! This will shave off a bit of time from my role update process :)
