### ISSUE TITLE
Name with umlaut results in a parsing error

### ISSUE THREAD

**Issue by gregdek** [ansible/galaxy-issues#13]
Fails: 
galaxy_info: 
author: Björn Dieding

Works: 
galaxy_info: 
author: Bjoern Dieding

See xrowgmbh/ansible-role-ntp: a17f64e

**Comment by chouseknecht** [comment]
For readme.md file Galaxy will now import unicode characters while still stripping HTML.

**Comment by gregdek** [comment]
Have added various umlauts in various places, and none of them kill anything, so I think that's good enough.

**Comment by gregdek** [comment]
Shipped!
