### ISSUE TITLE
Plural for 'minutes ago' is currently 'minutess ago'

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy-issues#130]
...for some reason, this always bugs me; I didn't see another bug report for it so I thought I'd post it:

It looks like the plural for the _time ago_ works correctly for `seconds` and `hours`, but not for `minutes`.

Here's what it looks like for values of `1` minute:

![screen shot 2016-02-20 at 2 57 54 pm](https://cloud.githubusercontent.com/assets/481677/13199134/6242b4a0-d7e2-11e5-96eb-1d5573cb94de.png)

...and for `2+` minutes:

![screen shot 2016-02-20 at 2 58 45 pm](https://cloud.githubusercontent.com/assets/481677/13199136/73eb6698-d7e2-11e5-99de-df006eaa6862.png)

**Comment by geerlingguy** [comment]
I guess this could be nicknamed 'snake-style' pluralization?

**Comment by chouseknecht** [comment]
Thanks for catching this. Fixed.

**Comment by geerlingguy** [comment]
@chouseknecht - thanks!
