### ISSUE TITLE
Galaxy user does not have access to repo

### ISSUE THREAD

**Issue by jeqo** [ansible/galaxy-issues#135]
Hi guys,

I have an issue with a couple of roles: When I try to import them, I get this message:

Starting import 3688: role_name=apache-kafka repo=jeqo/ansible-apache-kafka ref=
Retrieving Github repo jeqo/ansible-apache-kafka
Galaxy user jeqo does not have access to repo jeqo/ansible-apache-kafka 

These repositories are public and I have other roles that work ok. How can I fix this?

**Comment by chouseknecht** [comment]
This feels like the repo got renamed at some point. It was imported into Galaxy on 1/29 of this year with a repo name of `ansible-apache-kafka`. The repo name is now `ansible-role-apache-kafka`. This seems like a situation we didn't account for. 

I updated role 7288 to have a github_repo of 'ansible-role-apache-kafka'. An import should work now.

**Comment by chouseknecht** [comment]
This might be a minor bug. We connect GitHub repos to Galaxy via full name. How should we handle the repo full name changing on GitHub?

**Comment by jeqo** [comment]
Thanks, its working now. I have the same problem with this repo: 

```
 Starting import 3693: role_name=oracle-database repo=sysco-middleware/ansible-oracle-database ref=
Retrieving Github repo sysco-middleware/ansible-oracle-database
Galaxy user jeqo does not have access to repo sysco-middleware/ansible-oracle-database 
```

About this issue: maybe there is a way to get the current name from GitHub API, or you could add another option to 'role settings' and let the user decide.

Let me know if you're using https://developer.github.com/v3/repos/#get to get repo's name to give a try

**Comment by chouseknecht** [comment]
Looks like the name of the repo should be `ansible-role-oracle-database`. Update the role with the correct repo name. You should be able to import it now.
