### ISSUE TITLE
ansible-galaxy --version gives an error

### ISSUE THREAD

**Issue by pichlermi** [ansible/galaxy-issues#136]
Vagrant hates this:
$ ansible-galaxy --version
   Usage: ansible-galaxy [delete|import|info|init|install|list|login|remove|search|setup] [--help] [options] ...

   Options:
     -h, --help     show this help message and exit
     -v, --verbose  verbose mode (-vvv for more, -vvvv to enable connection
                 debugging)
     --version      show program's version number and exit
   ERROR! Missing required action

**Comment by chouseknecht** [comment]
Yes it does. Unfortunately this is part of a larger issue within ansible. Please add thoughts and comments to this issue: https://github.com/ansible/ansible/issues/12004.

Closing as this is part of a known issue/discussion within ansible core.
