### ISSUE TITLE
Readme markdown is not shown correctly (blockquote)

### ISSUE THREAD

**Issue by Yannik** [ansible/galaxy-issues#137]
Hi,

the blockquote in the README of this role:
https://galaxy.ansible.com/Yannik/relaymail/#readme, https://github.com/Yannik/ansible-role-relaymail

differes from how it is displayed on github. On github it correctly is a blockquote, on ansible galaxy the ">" chars are shown and there is no blockquote.

I also tried

```
> Line1
>
> Line2
```

Instead of

```
>Line1

>Line2
```

but that didn't work either.

**Comment by chouseknecht** [comment]
Looks like beach is clobbering the >, turning it into `&gt;`. Later when we run the text through markdown it of course doesn't know what to do with `&gt;`

**Comment by chouseknecht** [comment]
This is fixed at [galaxy-qa.ansible.com/chouseknecht/relaymail](https://galaxy-qa.ansible.com/chouseknecht/relaymail/). I forked the role and imported to test.

See the markdown here: https://raw.githubusercontent.com/chouseknecht/ansible-role-relaymail/master/README.md

**Comment by chouseknecht** [comment]
Will deploy this fix tonight and update the ticket.

**Comment by Yannik** [comment]
@chouseknecht Looks good to me!

What do you think about the links in the quote being embedded in an anchor element on github but not on ansible galaxy?

**Comment by chouseknecht** [comment]
If you put them in proper markdown syntax, they will work. I updated the QA
site: https://galaxy-qa.ansible.com/chouseknecht/relaymail/

On Wed, Mar 2, 2016 at 3:03 PM, Yannik notifications@github.com wrote:

> @chouseknecht https://github.com/chouseknecht Looks good to me!
> 
> What do you think about the links in the quote being embedded in an anchor
> element on github but not on ansible galaxy?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/galaxy-issues/issues/137#issuecomment-191403121
> .

## 

Chris Houseknecht
Principal Engineer
RedHat | Ansible http://ansible.com
919.803.9159 <9198039159> c

**Comment by Yannik** [comment]
@chouseknecht 
Yeah, I do know that (or expected it). Automatically doing it as done by github would just be a nice feature and provide parity with github.

**Comment by chouseknecht** [comment]
Deployed to production. Import your role again, and it should be good.
