### ISSUE TITLE
Markdown list-subelements are not rendered correctly

### ISSUE THREAD

**Issue by Yannik** [ansible/galaxy-issues#138]
Please compare https://github.com/Yannik/ansible-role-php-fpm#role-variables with https://galaxy.ansible.com/Yannik/php-fpm/

The sub-sub elements are incorrectly rendered as top-level list elements on galaxy.

**Comment by chouseknecht** [comment]
Indenting by 4 works.

Obviously  we're not pulling the HTML from the GitHub API, so you in some cases you have to follow strict markdown rules. At some point this may change. But for now, when something is not formatting correctly, please check to see if conforming the text to the slightly more strict markdown rules will do the trick. Apologies for the inconvenience.

**Comment by Yannik** [comment]
@chouseknecht 
I just tested this with the commonmark reference implementation (http://spec.commonmark.org/dingus/). Does work with 2 spaces. I know you are not pulling HTML, but if even the reference implementation supports it?

**Comment by chouseknecht** [comment]
See https://github.com/waylan/Python-Markdown/issues/3

**Comment by Yannik** [comment]
@chouseknecht 

Thanks. I will use the 4 spaces. 

However, there now seems to appear a bogus empty line after each list subelement?
See https://galaxy.ansible.com/Yannik/php-fpm/

This really seems to be a bug to me now.

Edit:
See this screenshot:
![picture](https://i.imgur.com/qap8Ain.png)

**Comment by chouseknecht** [comment]
I would agree that the spacing issue is a bug. Looks like an easy adjustment to our stylesheet. I'll see if I can clean that up this evening.

**Comment by chouseknecht** [comment]
Fixed.
