### ISSUE TITLE
Galaxy account dot trouble

### ISSUE THREAD

**Issue by orgoj** [ansible/galaxy-issues#142]
Hi,

I have old account michael.heca which is linked with github. Account with dot are unusable.
I create new account orgoj, linked with github. But login with github, log me to old michael.heca account.

How to change github link, or delete whole old account with dot?
Galaxy is now unusable for me.

Thanks

Michael Heca

**Comment by chouseknecht** [comment]
I deleted the old michael.heca account. Let me know, if that does not fix the issue.

**Comment by orgoj** [comment]
Thanks, now Github login working.
--mh
