### ISSUE TITLE
import of role with dependency fails

### ISSUE THREAD

**Issue by kostyrev** [ansible/galaxy-issues#144]
Hi!
I've got https://galaxy.ansible.com/kostyrevaa/koji-db
When I try to Re-import role it fails with:

```
Role dependency not found: patrik.uytterhoeven.PostgreSQL-For-RHEL6x
```

meta looks like this https://github.com/kostyrevaa/ansible-koji-db/blob/master/meta/main.yml#L17

I'm able to install the dependecy with

```
ansible-galaxy install patrik.uytterhoeven.PostgreSQL-For-RHEL6x
```

**Comment by chouseknecht** [comment]
The issue is that the namespace patrik.uytterhoeven contains a '.'  Pushed a fix for this. I forked the role and successfully imported it. 

Please, try the import again, and comment on the ticket or close.

**Comment by kostyrev** [comment]
Yeah, now it's working as expected.
Thank you, Chris!
