### ISSUE TITLE
Search for keyword + platform returning results for platforms not specified for search

### ISSUE THREAD

**Issue by robynbergeron** [ansible/galaxy-issues#146]
Originally seen here: https://twitter.com/leventyalcin/status/710452975978811393

But, verified this with repeating author's search:
- Keyword: nginx
- Platform: EL
- Sorted by relevance

A bunch of Ubuntu/Debian and not EL at all results were returned. Repeated with some different keywords (apache) and had a similar experience.

**Comment by chouseknecht** [comment]
I can reproduce as well. Definitely a bug.

**Comment by chouseknecht** [comment]
Fixed, and available for testing on the [QA site](https://galaxy-qa.ansible.com). The 'EL' platform did not work correctly because the Elasticsearch indexes require a minimum of 3 characters for a match. 'EL' is now indexed as 'Enterprise_Linux'.

**Comment by chouseknecht** [comment]
Fixed and pushed to production.
