### ISSUE TITLE
Debian invalid platforms

### ISSUE THREAD

**Issue by nlap** [ansible/galaxy-issues#149]
[My role](https://galaxy.ansible.com/nlap/graph_tool/) seems to have imported fine before, but I just noticed the latest import failed with the following errors:

> Invalid platform: Debian-stretch (skipping)
> Invalid platform: Debian-sid (skipping)

Can support for those platforms be added?

**Comment by chouseknecht** [comment]
Added.

**Comment by robynbergeron** [comment]
Done!
