### ISSUE TITLE
Add distro filter to search

### ISSUE THREAD

**Issue by gregdek** [ansible/galaxy-issues#15]
A common complaint is that Debian users can't easily find roles that are built for Debian distros, etc. We should have the data to add a filter, which could be a simple addition that could add a lot of value quickly.

**Comment by chouseknecht** [comment]
Completed in develop branch.  Will send you a link to a development instance where you can take a look.

**Comment by gregdek** [comment]
Looks pretty good overall.

One note: the Ubuntu/all search takes about 15 seconds, since it comes up with over 2000 roles. Is that likely to be more speedy on production?

**Comment by chouseknecht** [comment]
I see the same behavior.  Will take a look later today on the new production host.

**Comment by gregdek** [comment]
We got most of this into 1.0, but we've got some performance issues in 1.1 that we need to resolve.

**Comment by gregdek** [comment]
This is essentially done, but leaving open for 1.1 as a reminder to get rid of the "version" limiter (which is only present now to keep us from seeing terrible performance in large datasets.)

**Comment by chouseknecht** [comment]
The version limiter is removed.

**Comment by gregdek** [comment]
One thing: a lot of people may search for "Centos" or "RHEL" and not know that the proper distro tag for us is "EL". Let's add an alias that points those to "EL" in the same way that we point "Trusty" to "Ubuntu".

**Comment by chouseknecht** [comment]
Done.  Added 'alias' to the Platform data model and included in the autocomplete search index. Added 'centos rhel redhat' as the alias for EL. 

On the Browse Roles page start typing any of those values (centos, rhel, redhat) and EL will be presented in the autocomplete list for Platforms.

**Comment by robynbergeron** [comment]
Okay, this works.

My only concern here is that for people like me who type fast and hit enter -- I can type centos or rhel and it will come back with "no results" before the dropdown/autocomplete thing gets a chance to come up. 

I almost wonder if there would also be a way to return an error message of sorts saying "searching for centos or RHEL? Try searching for EL instead" for the case where people type quick and hit enter to search.

**Comment by chouseknecht** [comment]
That's not a bad idea.  Noodling on it.

**Comment by gregdek** [comment]
I think this is an important enhancement. We don't need to stop ship for this one, but we'll file it as a new enhancement request.

**Comment by gregdek** [comment]
In the meantime, :shipit:

**Comment by gregdek** [comment]
Shipped!
