### ISSUE TITLE
Role dependencies level limit ? 

### ISSUE THREAD

**Issue by support-capensis** [ansible/galaxy-issues#151]
Hi,

I have a role that depends from this kind of dependencies : 

role 1 => dependencies -> role 2
role 2 => dependencies -> role 3
role 3 => dependencies -> role 4

And i've this error during the downloading of this "role 4"

```
- downloading role 'role-4', owned by 
- sorry, role-4 was not found on galaxy.ansible.com.
- you can use --ignore-errors to skip failed roles.
```

Is there a known limitation about some levels of dependencies into galaxy ?

my version of ansible is 1.9.4, but same problem in a ansible 2.0 version

thx

**Comment by chouseknecht** [comment]
I don't know that there is a limitation. However, I'd be happy to poke at it and see if there is a limit or possible bug.  Can you share the top-level role that you're actually trying to install along with it's dependencies. It would be helpful to have an actual test case.

**Comment by gregdek** [comment]
@support-capensis If you need help with this, please provide the information requested by @chouseknecht. Thanks!
