### ISSUE TITLE
Website content

### ISSUE THREAD

**Issue by max-allan-surevine** [ansible/galaxy-issues#152]
The galaxy website has several typos on the intro page : 
 https://galaxy.ansible.com/intro#review

> There are mutliptle ways to gauge...

But there is only a single way to spell "multiple".

https://galaxy.ansible.com/intro#role-test

> Testing roles is a great practice, and a habbit we recommend.

Running a spell checker is a great practice and a habit I recommend. It gives readers confidence that code examples have no bugs in them if you can at least get the accompanying text right.

**Comment by chouseknecht** [comment]
Fixed and in production.
