### ISSUE TITLE
add FreeBSD 10.3 and OpenBSD 5.9 to platform list

### ISSUE THREAD

**Issue by nusenu** [ansible/galaxy-issues#153]
If you import a role you get these messages:

Invalid platform: FreeBSD-10.3 (skipping)
Invalid platform: OpenBSD-5.9 (skipping) 

https://github.com/nusenu/ansible-relayor/blob/master/meta/main.yml

**Comment by nusenu** [comment]
hi,
do you have an ETA for this?
thanks!

**Comment by chouseknecht** [comment]
Done
