### ISSUE TITLE
Option to be able to select specific tags with ansible-galaxy command?

### ISSUE THREAD

**Issue by Pseudonomy** [ansible/galaxy-issues#155]
Currently it doesn't seem to be possible to select specific tags with the `ansible-galaxy` command like it's possible with `ansible-playbook play.yml -i inventory.yml -t selected_tag_to_be_run`. Would be nice if this feature could be added, would allow for more flexibility in deploying playbooks.

**Comment by gregdek** [comment]
So I think that you may be confusing two concepts: the tag within an Ansible playbook and the tags/categories of Ansible Galaxy are unrelated. What specific use case are you trying to solve?
