### ISSUE TITLE
Versioning of roles

### ISSUE THREAD

**Issue by gregdek** [ansible/galaxy-issues#168]
Time to start figuring this out. Unless there's significant backlash, because we live in the Python world here at Ansible, we're likely to implement PEP-440 for versioning:

https://www.python.org/dev/peps/pep-0440/

**Comment by geerlingguy** [comment]
Yeesh, that reads like an IETF RFC... is there a good comparison/contrast between PEP-440 and [Semantic Versioning](http://semver.org/)? It seems like at least the core components of semver would be acceptable (e.g. `[major].[minor].[patch]`).

Edit: I did see a [Semantic Versioning](https://www.python.org/dev/peps/pep-0440/#semantic-versioning) section. Looks like the core part is fine, but tags like `1.0.0-beta1` would not be (that would presumably be `1.0.0.b1`?).

**Comment by gregdek** [comment]
Notable: this is the mechanism for PyPi versioning, and this spec was written by the author of PyPi.

**Comment by geerlingguy** [comment]
@gregdek - I know you closed https://github.com/ansible/galaxy-issues/issues/165 in favor of this issue, but would this issue technically cover some sort of locking mechanism as well? E.g. If I wanted the latest of a "3.1.x" branch (and could choose 'stable', 'dev', 'alpha' etc.), is that the desired outcome of this issue? Or is it more just agreeing to or documenting the use of PEP 440?

If the latter, could we leave the Lockfile/version pinning issue open?

**Comment by gregdek** [comment]
We can reopen if you like, sure. I suppose they are separate issues.

**Comment by goozbach** [comment]
I'd vote for limited semvers as defined in pep-440  but I have simple needs and don't know most edge cases.

**Comment by bcoca** [comment]
We already allow 'commit sha' as a 'role version'

**Comment by chouseknecht** [comment]
This issue was moved to ansible/galaxy#83
