### ISSUE TITLE
Use SPDX license identifiers

### ISSUE THREAD

**Issue by ypid** [ansible/galaxy-issues#169]
SPDX license identifiers seem to have become the default license identifier format AFAIK. I think it would make sense to use them also for `meta/main.yml`?

As of Ansible 2.1 `ansible-galaxy init` generates:

``` YAML
  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)
```

With this proposal implemented, this could look like:

``` YAML
  # Some suggested licenses:
  # - BSD-2-Clause (default)
  # - MIT
  # - GPL-2.0
  # - GPL-3.0
  # - AGPL-3.0
  # - GPL-3.0+
  # - Apache-2.0
  # - CC-BY-SA-4.0
  license: AGPL-3.0
```

The current format is ambiguous to say the least.

Ref: https://spdx.org/licenses/

**Comment by chouseknecht** [comment]
This issue was moved to ansible/galaxy#82
