### ISSUE TITLE
Output name for ansible-galaxy download

### ISSUE THREAD

**Issue by lowks** [ansible/galaxy-issues#172]
It would be nice if `ansible-galaxy` had a `-o` switch where I can specify the downloaded folder name for example: 

`ansible-galaxy install genzouw.postfix -p . -o postfix`

This is if I would rather have the downloaded folder be called just `postfix` instead of `genzouw.postfix`

**Comment by chouseknecht** [comment]
This functionality is already available using the _name_ attribute in a requirements file.

For example, if you specify the following in the requirements file:

```
- src: chouseknecht.pgclone
  name: pgclone
```

The role will be downloaded and placed in a directory called _pgclone_.

The docs site show an example here: http://docs.ansible.com/ansible/galaxy.html#advanced-control-over-role-requirements-files
