### ISSUE TITLE
Galaxy tags not being ordered by release date or natural semantic version ordering

### ISSUE THREAD

**Issue by ricardclau** [ansible/galaxy-issues#173]
Hi

We just released tag 1.10.0 of https://galaxy.ansible.com/carlosbuenosvinos/ansistrano-deploy/ and we have noticed the tag list is ordered by "string" order rather than the real natural ordering (1.10 after 1.9) or even better the release date

Any chances this can be improved?

![image](https://cloud.githubusercontent.com/assets/613725/17114839/9da3ab30-52a8-11e6-9883-7903d322d75d.png)

**Comment by chouseknecht** [comment]
Fixed. Release tags are now sorted by desc release date.
