### ISSUE TITLE
/etc/ansible permission issue displays API timeout error message

### ISSUE THREAD

**Issue by Brunty** [ansible/galaxy-issues#178]
During some recent upgrades of packages (using brew on OS X) somehow the `/etc/ansible` folder on my system ended up with the following permissions: `d-wx--x--x` for my user (`brunty` in this case) - meaning I couldn't read what was in there (not sure how it happened, could have been my fault but I'm unsure of the cause at this point)

I could install roles with `sudo ansible-galaxy install user.role` (or do it inside a vagrant box that had a fresh install of ansible etc) but regular `ansible-galaxy install user.role` on OS X (host machine) gave the error message:

```
> ansible-galaxy install geerlingguy.php -vvvv --force
No config file found; using defaults
Opened /Users/brunty/.ansible_galaxy
Installing role geerlingguy.php
Opened /Users/brunty/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
 [WARNING]: - geerlingguy.php was NOT installed successfully: The API server (https://galaxy.ansible.com/api/) is not responding, please try again later

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

I spent hours trying to work out what was wrong with the connection to the API (as I wasn't aware that it was a permissions issue with the folder). I saw suggestions of re-installing ansible, re-installing python / pip, trying proxies. But in the end it was the permissions on my `/etc/ansible/` folder that did it.

It seems that the error message displayed isn't correct for the situation I found myself in, as there was no problem connecting to the API?

**Comment by s-hertel** [comment]
Hi!

Thanks very much for your submission to Ansible. It sincerely means a lot to us.

I have a couple follow-up questions:
1. As far as I am aware, ansible-galaxy should not be the cause of the changed /etc/ansible permissions. Using brew to install (and possibly if you upgrade) may cause some issues however. Did you install/upgrade Ansible with brew?
2. Were you able to install roles without sudo prior to upgrading? You may also be able to fix the issue running a Permissions Repair from Disk Utility.

We will definitely see your comments on this issue when reading this ticket, but may not be able to reply promptly. You may also wish to join one of our two mailing lists which are very active:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
Thank you once again for this and your interest in Ansible!

**Comment by Brunty** [comment]
The permissions weren't an issue with ansible or galaxy, it was likely during an upgrade via brew that they got changed.

1) I upgraded ansible with brew
2) Prior to upgrading everything was fine, I could install roles without sudo without a problem, and once I changed the permissions back so that my user could access the directory, it worked again.

**Comment by Brunty** [comment]
As a note as well, I ran disk permissions and it wasn't that - it didn't fix it, but that's not the focus of the issue I raised.

Probably bad wording on my part, but it was more that the error message displayed is completely wrong when it was a permissions problem on the folder.

Surely it shouldn't show an API timeout message when the problem was local permissions?

**Comment by bcoca** [comment]
API timeout would impact first as disk permissions would not be checked until it attempted to write to the directory.

**Comment by CelestP** [comment]
I am having a similar problem:  
I am on CentOS 6.7:   I have installed ansible several different ways  
first using yum install and then just using pip install ansible. 
The problem is I am able to use ansible-galaxy init as  root or sudo ,  however when I use a non-root account I get the following: 

been modified there already.
(ansible) [pantophl@4nlomarzhan1 ansible]$ ansible-galaxy init xa
ERROR! The API server (https://galaxy.ansible.com/api/) is not responding, please try again later
(ansible) [pantophl@4nlomarzhan1 ansible]$ ansible-galaxy -vvvvvvv init xb
Using /home/pantophl/.ansible.cfg as config file
Opened /home/pantophl/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com

## ERROR! The API server (https://galaxy.ansible.com/api/) is not responding, please try again later

**Comment by chouseknecht** [comment]
@CelestP @Brunty, Can you provide the version of Ansible you're running? 

This appears to be work correctly in 2.1.1.0 and 2.3.

I attempted to reproduce with 2.1.1.0:

```
$ ansible-galaxy install geerlingguy.nodejs -vvvv --force
Using /etc/ansible/ansible.cfg as config file
Opened /Users/chouseknecht/.ansible_galaxy
Installing role geerlingguy.nodejs
Opened /Users/chouseknecht/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
- downloading role 'nodejs', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=nodejs
https://galaxy.ansible.com/api/v1/roles/465/versions/?page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-nodejs/archive/3.3.0.tar.gz
- extracting geerlingguy.nodejs to /etc/ansible/roles/geerlingguy.nodejs
 [WARNING]: - geerlingguy.nodejs was NOT installed successfully: Could not update files in /etc/ansible/roles/geerlingguy.nodejs: [Errno 13] Permission denied: '/etc/ansible/roles/geerlingguy.nodejs'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
~ $ ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
~ $ source ./projects/ansible/hacking/env-setup
```

Also attempted to reproduce with 2.3:

```
$ ansible-galaxy install geerlingguy.nodejs -vvvv --force
Using /etc/ansible/ansible.cfg as config file
Opened /Users/chouseknecht/.ansible_galaxy
Installing role geerlingguy.nodejs
Opened /Users/chouseknecht/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
- downloading role 'nodejs', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=nodejs
https://galaxy.ansible.com/api/v1/roles/465/versions/?page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-nodejs/archive/3.3.0.tar.gz
- extracting geerlingguy.nodejs to /etc/ansible/roles/geerlingguy.nodejs
 [WARNING]: - geerlingguy.nodejs was NOT installed successfully: Could not update files in /etc/ansible/roles/geerlingguy.nodejs: [Errno 13] Permission denied: '/etc/ansible/roles/geerlingguy.nodejs'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

$ ansible --version
ansible 2.3.0 (galaxy_server a32e48555d) last updated 2016/10/11 15:55:25 (GMT -400)
  lib/ansible/modules/core: (detached HEAD e4c5a13a7a) last updated 2016/10/03 09:29:48 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD df35d324d6) last updated 2016/10/03 09:29:48 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by Brunty** [comment]
I'll have a look when I get some time (then maybe this will be re-opened)

I fixed the issue by fixing the permissions, so will need to break the permissions in order to re-create the problem, and since then I've updated ansible etc. So it's possible I may not be able to re-create the problem.
