### ISSUE TITLE
Galaxy not automatically importing roles after Travis CI notifications

### ISSUE THREAD

**Issue by geerlingguy** [ansible/galaxy-issues#182]
It looks like some of my roles are no longer getting imported automatically after new tagged releases in Travis CI.

I had to manually trigger an import inside Galaxy for my `geerlingguy.security` role earlier today, and I just checked and even though my `geerlingguy.jenkins` role was built from the latest tag, `2.5.0` ([see Travis build here](https://travis-ci.org/geerlingguy/ansible-role-jenkins/builds/152785943)), it was never imported into Galaxy ([see Galaxy role status here](https://galaxy.ansible.com/geerlingguy/jenkins/)).

I've not imported this role manually yet in case that can help with debugging anything... but let me know if I should manually import.

It looks like it may have been a little while since automatic role import has been working, as I just noticed that Galaxy is still listing an older `2.3.0` release as the latest—`2.4.0` was also released in the interim.

**Comment by geerlingguy** [comment]
Could this be related to:
- https://github.com/ansible/galaxy-issues/issues/176
- https://github.com/travis-ci/travis-ci/issues/6435

**Comment by xenithorb** [comment]
I have also noticed this behavior. The badge is also picking up _any failed build_ for some reason, too, which is disconcerting. https://galaxy.ansible.com/RocketChat/Server/

**Comment by chouseknecht** [comment]
Builds are working again, at least I'm seeing them work on our QA site https://galaxy-qa.ansible.com.

If you look in the API at the RocketChat role [here](https://galaxy.ansible.com/api/v1/roles/?namespace=RocketChat), the URL for Travis status is: https://travis-ci.org/RocketChat/Rocket.Chat.Ansible.svg?branch=letsencrypt. When we display the image on Galaxy, we wrap it in a link taken from the most recent notification received from Travis: https://galaxy.ansible.com/api/v1/roles/6478/notifications/. Point being that it's not random; however, if we fail to receive a build notification from Travis, then yes, the link would point to an outdated build. 

And actually, now that I look at the notification history for this role, it looks like updates are working in production as well. The most recent notification landed on 9/26, which seems to align with the Travis history.

I think we can close this.

**Comment by xenithorb** [comment]
I don't understand why it would point to non-production builds automatically. So what you're telling me is, if I push to an intentionally broken working branch and it builds, the build will appear broken to galaxy.ansible?

**Comment by geerlingguy** [comment]
@xenithorb - I believe that's due to a limitation in Travis, not Galaxy. Regardless, Galaxy won't do anything with broken branches—it only pulls in tags, not branches, and will show the README and other data from the latest tag available.
