### ISSUE TITLE
REST API for role registration would be super helpful and shiny

### ISSUE THREAD

**Issue by emonty** [ansible/galaxy-issues#185]
The current mechanism for registering roles with galaxy seems like it would work well for folks who have a reasonable amount of repos associated with them in github. But it's got a couple of issues that we've run in to over in the land of holy-crap-you-have-how-many-repos.

The first of the issues is that the registration page essentially just hangs until the end of time. I'm guessing this is because OpenStack has about 1500 repos that the importer needs to look through - not to mention that my user is also associated with jenkinsci - which has quite a ton too.

The second issue is that the process involves clicketty-clicketty in a web page. This is bad for automation. The rest of our infrastructure happens to be driven by yaml files in git repos that undergo code review and stuff - so when we then have to have a human click on a web page to get something registered somewhere, it makes bunny rabbits sad.

The third issue, which might just be part of the second issue, is that we have 48 roles that are in repos that are not named ansible-role-$foo. A good for-instnace is "openstack-ansible-os_swift" The importer will not auto-find it. If it did, we'd still have to click through and give it an alias name.

Finally - and I know I'm not going to win this one, but I might as well write it down - we don't actually use github for anything other than as a read-only mirror, so galaxy being tied to github oauth is ... weird. It's not unworkable - it's just annoying when we have to interact with a closed-source platform to publish open source roles.

What I really want is a REST API that does something like this:

"hey galaxy, there is a git repository at $internet_location that is a role that should be named $role_name"

If we had that, we could use it in our repo-creation automation to register the repo with galaxy. Of course, I know that there are $reasons why github is being used as a backend - so an alternate would be:

"hey galaxy, the github repo $repo contains a role that should be named $role_name"

In any case - any sort of API that we can call to explicitly register a thing with galaxy and give it a name that does not involve clicking on web pages would be spectacular.

PS. The scan-your-repos page finally returned ... I think it took 30 minutes to run.

**Comment by odyssey4me** [comment]
👍  This would be very useful for the OpenStack-Ansible community.

**Comment by emonty** [comment]
So - sniffing the network traffic from the web app, it looks like there is one, it's just not documented. For instance:

POST https://galaxy.ansible.com/api/v1/imports/
{"github_user":"openstack","github_repo":"openstack-ansible-os_cloudkitty","alternate_role_name":"os_cloudkitty"}

Is that the web ui is doing when you click the thing to change the name.

That's super easy to deal with - pending some limited instructions on how auth should work. (I see the login/response handshake for the webapp, but I'm not sure if that's the 'right' way to deal with it from a script)

**Comment by robynbergeron** [comment]
🍆 ✨ 🎉 

Hmm, my magic wand doesn't seem to be working. Perhaps because it's an eggplant? Not sure. 😄 

@emonty -- thanks for filing (and to @odyssey4me for chiming in as well). Also, note that the "closed source platform" detail is in progress, and once that is unlocked Real Soon Now then not-github support could be a thing. 

Marking as an enhancement for the moment :)

**Comment by bcoca** [comment]
The ansible-galaxy command line can be used to bulk import roles, this was added in 2.0

**Comment by chouseknecht** [comment]
@emony, @robynbergeron 

As Brian mentioned, you could of course use the ansible-galaxy CLI to import a role. It is also possible to access the Galaxy API directly, and POST requests. 

The [galaxy-import-role](https://galaxy.ansible.com/chouseknecht/galaxy-import-role/) can also be used to automate Galaxy imports. Just pass it an array of repositories, and it'll take care of the rest. It's an example of how to access the API suing the Ansible `uri` module.

Or, if you want to _role_ your own... (see what I did there?)

To authenticate to the API, all you need is a GitHub [personal access token](https://help.github.com/articles/creating-an-access-token-for-command-line-use/). Then POST to https://galaxy.ansible.com/api/v1/tokens/ with a request body:

```
{
    "github_token": "<your GitHub token>"
}
```

That will return the following response: 

```
{
    "token": "< your Galaxy token >",
    "username": "< your Galaxy username >"
}
```

To create the import request, POST to /api/v1/imports/ with an Authorization header, like the following:

```
{
    "Authorization": "Token <your Galaxy token>"
}
```

The request body will consist of the following:

```
{
    "github_user": "<the repo user or organization>",
    "github_repo": "<the repo name>",
    "github_reference": "<the branch name to import>"
}
```

And yes, this is all GitHub centric. The Galaxy code will become OSS during AnsibleFest next week, so perhaps someone in the community will take it upon themselves to add support for other VCSs.
