### ISSUE TITLE
No way to see what platforms are available to meta

### ISSUE THREAD

**Issue by jaywink** [ansible/galaxy-issues#188]
This list is generated with the role initialization, yes. But later, wanting to maybe add new platforms to your now expanded role (since of course commented ones were removed), there is no way to find out what the platforms accepted are, except by initing a new role.

A list somewhere, Ansible Galaxy or documentation would help.

**Comment by ericsysmin** [comment]
I completely agree.

**Comment by chouseknecht** [comment]
You can look at the platforms in the API at https://galaxy.ansible.com/api/v1/platforms. See the list of versions for a specific platform by searching for name: https://galaxy.ansible.com/api/v1/platforms/?name=EL

**Comment by jaywink** [comment]
@chouseknecht so this information is on the Ansible Galaxy site or documentation? If not this issue is hardly closed.
