### ISSUE TITLE
No roles found in your public GitHub repositories

### ISSUE THREAD

**Issue by eriksencosta** [ansible/galaxy-issues#192]
I got this error while trying to add a role in Ansible Galaxy.

I suppose this is similar to #108. I deleted my GitHub account (with this same username) that was associated with my Ansible Galaxy account earlier this year.

I already revoked/granted Galaxy's as an authorized application.

**Comment by chouseknecht** [comment]
There were two GitHub accounts in Galaxy associated with the name 'eriksencosta'. Removed both of them along with the social tokens. 

Try to log in again, and update this ticket with the result.

Thanks!

**Comment by eriksencosta** [comment]
@chouseknecht it works!

Thanks!
