### ISSUE TITLE
Galaxy does not seem to accept the new syntax structure for defining dependencies

### ISSUE THREAD

**Issue by 030** [ansible/galaxy-issues#193]
http://serverfault.com/questions/803079/what-is-the-correct-syntax-of-defining-role-dependencies-in-the-meta-main-yml-in/805531#805531

```
 Invalid role dependency: {'src': '030.sensu-install', 'version': '0.1.1', 'name': '030.firewall'} (skipping) (error: 'role' keyword was not found in the role dictionary)
Role dependency not found: {'src': '030.sensu-install', 'version': '0.1.1', 'name': '030.firewall'}
Invalid role dependency: {'src': '030.sensu-plugin-install', 'version': '0.1.0', 'name': '030.sensu-client'} (skipping) (error: 'role' keyword was not found in the role dictionary)
Role dependency not found: {'src': '030.sensu-plugin-install', 'version': '0.1.0', 'name': '030.sensu-client'}
Invalid role dependency: {'src': 'geerlingguy.ntp', 'version': '1.3.0', 'name': 'geerlingguy.ntp'} (skipping) (error: 'role' keyword was not found in the role dictionary)
Role dependency not found: {'src': 'geerlingguy.ntp', 'version': '1.3.0', 'name': 'geerlingguy.ntp'} 
```

http://serverfault.com/a/805531/215599

**Comment by chouseknecht** [comment]
In the celery tasks we will use "from ansible.playbook.role.requirement import RoleRequirement" to 
correctly parse a dependency and determine its src. Working on this now.

**Comment by 030** [comment]
@chouseknecht I have tried to import the roles, but it fails. How could I help testing it?

**Comment by bcoca** [comment]
The deprecation warning was happening in some cases incorrectly, that has been fixed in devel (2.2), src is not currently needed in dependencies and is unused.

**Comment by chouseknecht** [comment]
@030 the fix has been deployed to our QA site: https://galaxy-qa.ansible.com.

**Comment by 030** [comment]
@chouseknecht I have imported the roles on the QA site and it succeeded. The issue seems to be solved (+1). Thank you.

**Comment by chouseknecht** [comment]
This is fixed on the ansible-playbook side as well in the 'devel' branch. It was fixed by [this PR](https://github.com/ansible/ansible/pull/17818)

**Comment by 030** [comment]
Verified that the import work on https://galaxy.ansible.com as well

**Comment by chouseknecht** [comment]
The fix on the Galaxy side is now in production.
