### ISSUE TITLE
Update Galaxy Username

### ISSUE THREAD

**Issue by vincetse** [ansible/galaxy-issues#194]
Is there any way to update my Galaxy username to match my Github username (which I have updated)?

**Comment by chouseknecht** [comment]
What is your Galaxy username, and what is your GitHub username?

**Comment by chouseknecht** [comment]
Looks like your Galaxy username is 'thelazyenginerd'. I changed your username 'vincetse'. Not sure why that matters, as you can log in with your GitHub account, and any roles you import will import to the GitHub namespace, which would most likely be 'vincetse'.

**Comment by vincetse** [comment]
Thank you.  You did exactly what I was asking for.
