### ISSUE TITLE
Getting 500 error when importing role from GitHub

### ISSUE THREAD

**Issue by icamys** [ansible/galaxy-issues#195]
I had a registered role `ansible-role-nodejs` in galaxy. I've deleted the git repo and after that I removed it from registered roles in galaxy.

After that I've forked the `geerlingguy/ansible-role-nodejs` and updated the list of the repos in galaxy. As expected, `ansible-role-nodejs` has appeared in my roles list as unregistered.

When I clicked the trigger to import a role from GitHub (in my case it's `icamys.ansible-role-nodejs`), I got 500 server error in the devtool, network tab .

 I've updated the page and retried to import the role a few times. Looks like it's a server-side issue.

**Comment by chouseknecht** [comment]
I believe this is fixed now, at least in the UI.

If you go to My Roles and remove a role where the repository no longer exists on GitHub, the resulting 500 error is trapped and a notice is displayed asking you to click on the _refresh_ button. Previously the error was not trapped and the page sort of froze up.

Click on the refresh button now updates your roles to reflect what's actually found in GitHub. It's now smart enough to delete roles that no longer exist in GitHub, and updates the attributes of roles where the GitHub repository has been renamed.

If you find that there is still an issue, please re-open.

**Comment by icamys** [comment]
Looks like everything works fine now. Thanks!
