### ISSUE TITLE
Galaxy name conflict

### ISSUE THREAD

**Issue by Fale** [ansible/galaxy-issues#201]
This bug is against https://github.com/ansible/galaxy, but it has no issue enabled yet and @jimi-c told me to open it here.

The problem is that his module uses the name 'galaxy', which is already used by https://pypi.python.org/pypi/galaxy.
In case the pypi galaxy module is installed, this would conflict with it, due to how python resolves dependencies.

The solution is probably to rename Ansible galaxy to ansible-galaxy or ansible-galaxy-server so that it does not conflict. Also, even if Ansible Galaxy will not be published via pypi, "reserve" the name could be a sane idea to ensure the problem will not occur again

**Comment by gbraad** [comment]
I agree with the above assessment; using galaxy is a too generic name and it would be best to use ansible-galaxy instead

**Comment by chouseknecht** [comment]
The name galaxy-server has been reserved. At some point the project will be renamed, if it turns out we need to push releases to pypi.

**Comment by Fale** [comment]
This actually does not solve the current problem
