### ISSUE TITLE
Unable to login or import

### ISSUE THREAD

**Issue by woohgit** [ansible/galaxy-issues#202]
In the last 24hrs, logging is not always working, most of the time it throws an 500 error, and import isn't working neither. I click on the refresh and it's just spinning spinning and it logs me out after a few seconds/minutes.

Is everything OK on your side?

**Comment by chouseknecht** [comment]
I just opened a new browser, cleared the cache, and logged in with no issues. I can import roles without any problem. 

Noticing in the logs that you have somehow exceeded the rate limit for your GitHub id:

{u'documentation_url': u'https://developer.github.com/v3/#rate-limiting', u'message': u'API rate limit exceeded for woohgit.'}

**Comment by woohgit** [comment]
Interesting. I've just created an API key, I didn't have it before. Any hint what to do?

It logs me out every time.

I now try with the ansible-galaxy command line, it stuck at the `Retrieving Github repo woohgit/ansible-role-docker-gc` line..

**Comment by woohgit** [comment]
The api.github.com/rate_limit seems to be Ok

```
{
  "resources": {
    "core": {
      "limit": 60,
      "remaining": 58,
      "reset": 1476750378
    },
    "search": {
      "limit": 10,
      "remaining": 10,
      "reset": 1476746919
    }
  },
  "rate": {
    "limit": 60,
    "remaining": 58,
    "reset": 1476750378
  }
}
```

**Comment by chouseknecht** [comment]
Well, if I query the GitHub API using the Oauth token we have for your account, I still get the rate limit exceeded message.

**Comment by chouseknecht** [comment]
Don't know if it makes a difference, probably not, but I deleted the Oauth token we have for your account.

**Comment by woohgit** [comment]
Ok let me check.

**Comment by woohgit** [comment]
I have been redirected to the Authorize Galaxy page, clicked on Authorize... 

result: 

500 Server Error
An error occurred while loading the requested page. Please report this error at Galaxy Issues.

**Comment by woohgit** [comment]
Can't even login using ansible-galaxy:

``` bash
ansible-galaxy login --github-token=xxx --server=https://galaxy-qa.ansible.com                           
ERROR! Unexpected Exception: HTTP Error 400: BAD REQUEST
to see the full traceback, use -vvv
```

**Comment by woohgit** [comment]
Are you sure that it is not some broken retry in the galaxy site that retries and retries until I get the rate limit?

Last I tried to login around 12 hrs ago, then I went to sleep, woken up, tried to login again, and got the 500, so I assume something is not 100% on your side. The command line isn't working either. It is using my personal token, but just hangs there. Don't even give an error message or anything.

I even revoked the permissions from the Galaxy on github, it's re-added again, but still no luck with the login or import.

I'll leave for another 8 hrs and retry it later. I hope this issue will go away, although 20 hrs has passed since my first try and getting a bit frustrated.

**Comment by woohgit** [comment]
Something has happened finally!

My new roles are visible on the galaxy site and I'm able to login but only on galaxy-qa.ansible.com, galaxy.ansible.com still does not show my new repos and it sometimes logs me out. Usually happens after I hit the refresh repositories button..

**Comment by woohgit** [comment]
So I tried to reproduce it again. I was able to login, it kept me logged in for more than 1 hour. After I hit the refresh repositories, it starts spinning and a few minutes later it logs me out.

So I have a feeling that the repository refresh does not work as expected and it sends too many API requests to github. Can you check what's the issue with it?

**Comment by chouseknecht** [comment]
@woohgit noticing you're in two organizations - jenkins and cloudbees. Together that's a lot of repositories that you likely have access to. The jenkins org has 84 pages. When you click the Refresh button on _My Roles_, Galaxy looks through all of those to find repos that _look like_ roles. It sends at least one request per repo to see if the repo has a 'meta/main.yml' file.

The very first time you log into Galaxy your repo cache is empty, so Galaxy will perform a refresh. The next time you log in, if there are entries in the cache, a refresh will not be performed. You currently have 2 entries in the cache, an the cache does not expire or get flushed. After a change I made last night, subsequent refreshes are only performed when you click the Refresh button on _My Roles_.  

Sifting through the server logs, I'm not seeing anything that looks suspicious. You get a total of 5,000 API requests per hour. Not sure how many Galaxy is using (when you click Refresh), since I can't see the total number of repos.

Is it possible that some other app, bot or CI/CD process is also using your GitHub creds to access the API?

**Comment by woohgit** [comment]
@chouseknecht thanks for the info.

I have access to more than ~2000 repos probably. Nothing else is using my github credentials. 

Isn't it possible to add a new feature to Galaxy (web) to be able to provide the repo URL instead of scanning and analyzing all the public repos? This feature is available in the command-line tool, although the login with 2FA only works with the galaxy-qa.ansible.com URL, so I can't use the command line tool to login/import on the galaxy site, only on the galaxy QA site.

**Comment by woohgit** [comment]
This morning after hitting the refresh button the new ansibe repos appeared on the website so I was able to import them finally.

**Comment by chouseknecht** [comment]
Not sure what you mean by "although the login with 2FA only works with the _galaxy-qa.ansible.com_ URL". It _should_ work with _galaxy.ansible.com_. If it's not working, then we definitely need to fix that. I'm actually going to test it now while I write this, so please continue reading...

The `ansible-gaalxy` command receives a token from the Galaxy server and stores it in ~/.ansible_galaxy. Unfortunately I don't think it tracks the Galaxy server from which the token was received, so if you authenticated with _galaxy-qa_, then the token in that file would only work with the _galaxy-qa_ server. If that's the case, I would start by deleting ~/.ansible_galaxy. 

Then do the following to authenticate with _galaxy.ansible.com_:
1. Run `ansible-galaxy login`. This will prompt you for your GitHub username/passwod. -OR- run `ansible-glaxay login --github-token <xxx your token here xxxx>`. If you want to use a token, create a fresh Personal Access Token, where the scope includes: _public_repo_ and _user:email_. 
2. Run `ansible-galaxy import <github_user or org> <github_repo>`

The above will start the import and wait for the results. 

I did the steps above using the default server _galaxy.ansible.com_, and it works just fine. Here are my results:

```
$ ansible-galaxy import chouseknecht ansible-koji-db
Successfully submitted import request 31226
Starting import 31226: role_name=ansible-koji-db repo=chouseknecht/ansible-koji-db
Retrieving Github repo chouseknecht/ansible-koji-db
Accessing branch: master
Parsing and validating meta data.
No issue tracker defined. Enable issue tracker in repo settings, or provide an issue tracker in meta data.
Parsing galaxy_tags
Found categories in meta data. Update the meta data to use galaxy_tags rather than categories.
Parsing platforms
Adding dependencies
Parsing and validating README
Adding repo tags as role versions
Import completed
Status SUCCESS : warnings=2 errors=0
```

Please let me know, if you're not able to get this to work. I tested with the latest code found in the _devel_ branch at _ansible/ansible_.

Also, the import will work with any GitHub repo that contains a meta/main.yml file. It does not have to be a repo that was previously imported using the Galaxy web site. It can be a brand new repo that Galaxy has never seen. If you use the CLI, then you can avoid logging into the UI altogether and bypass the GitHub API rate limiting issue. 

For what it's worth, there is a role you can use to automate imports as well - https://galaxy.ansible.com/chouseknecht/galaxy-import-role/

**Comment by woohgit** [comment]
It's working now. It wasn't working yesterday. I got Bad Request 400 errors every time when I tried to auth against galaxy.ansible.com but was working with galaxy-qa.

Also this note is a bit misleading:

```
The login command in Ansible 2.0 requires using the Galaxy 2.0 Beta site. Use the --server option to access https://galaxy-qa.ansible.com. You can also add a server definition in the [galaxy] section of your ansible.cfg file.
```

So why the login command requires to use the Galaxy beta site?

**Comment by chouseknecht** [comment]
What version of Ansible are you using? Are you using 2.0? When we first introduced the `login` command, it was a _beta_ thing that only worked with _galaxy-qa_. That has since gone away.

**Comment by woohgit** [comment]
Ah ok. I though it's for all 2.0+.

That note should be removed now I think.

**Comment by chouseknecht** [comment]
O. I see that in our docs. Yeah, that should go away. I'll fix that. Thank you for pointing that out.

**Comment by woohgit** [comment]
Cool thanks.

I think this issue should be closed. Everything seems to work now.

**Comment by chouseknecht** [comment]
Awesome! Thank you for you patience and help!
