### ISSUE TITLE
Install ansible-galaxy (only galaxy) on Windows

### ISSUE THREAD

**Issue by Oliboy50** [ansible/galaxy-issues#204]
## Why

Because now that `Vagrant` allows to provision VMs without having to install `ansible` on the host machine... the only thing missing to fully support Windows (as host) is to be able to run `ansible-galaxy` on Windows (to easily download ansible roles that will be run in Vagrant).

Would be an awesome feature for developers, trust me.

**Comment by chouseknecht** [comment]
Curious if you could run `ansible-galaxy` from within a container on a Windows host. Presumable you can run Docker on Windows? Maybe not? I don't know. If you can, you could use the [ansible/ansible-container-builder](https://hub.docker.com/r/ansible/ansible-container-builder/) image, in which case something like the following might work:

```
docker run -v <your roles path>:/etc/ansible/roles ansible/ansible-container-builder ansible-galaxy install geerlingguy.apache
```

**Comment by Oliboy50** [comment]
@chouseknecht thanks, you're right, but it seems a bit overkill to force a user to install Docker For Windows (even if it should be installed by default on Windows IMHO) to be able to run `ansible-galaxy`... (I mean, run a VM to be able to run a VM... sounds weird)

Anyway, I found this configuration key in the Vagrant `ansible_local` provisionning: `galaxy_role_file` where you can point to a galaxy YML file... (of course, this is not documented anywhere...)

This (almost) completely solve my problem, so I'll close this thread.

But still, this would be really nice to be able to install `ansible-galaxy` on Windows 😋
