### ISSUE TITLE
Error 500 on signup using GitHub

### ISSUE THREAD

**Issue by dmishh** [ansible/galaxy-issues#207]
<img width="455" alt="screen shot 2016-10-21 at 11 04 33 pm" src="https://cloud.githubusercontent.com/assets/822562/19609996/ca32c74c-97e2-11e6-8192-a6efaf4f44a4.png">

**Comment by ericsysmin** [comment]
May be related to the Dyn attack against GitHub right now.

**Comment by dmishh** [comment]
@ericsysmin yeah, probably. Works already, btw.
