### ISSUE TITLE
Could not process data from the API server (https://galaxy.ansible.com/api/): the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by teohhanhui** [ansible/galaxy-issues#209]
python 3.5.2
ansible 2.2.0.0

```
~/pelangi-campaign/pelangicampaign.org/trellis$ ansible-galaxy -vvvv install -r requirements.yml
Using /home/teohhanhui/pelangi-campaign/pelangicampaign.org/trellis/ansible.cfg as config file
Opened /home/teohhanhui/.ansible_galaxy
found role {'name': 'composer', 'scm': None, 'version': '1.2.7', 'src': 'geerlingguy.composer'} in yaml file
found role {'name': 'ntp', 'scm': None, 'version': '0.3.0', 'src': 'resmo.ntp'} in yaml file
found role {'name': 'logrotate', 'scm': None, 'version': 'fc3ea4', 'src': 'nickhammond.logrotate'} in yaml file
found role {'name': 'swapfile', 'scm': None, 'version': 0.4, 'src': 'kamaln7.swapfile'} in yaml file
found role {'name': 'geerlingguy.daemonize', 'scm': None, 'version': '1.1.0', 'src': 'geerlingguy.daemonize'} in yaml file
found role {'name': 'mailhog', 'scm': None, 'version': '1.1.0', 'src': 'geerlingguy.mailhog'} in yaml file
Installing role composer 
Opened /home/teohhanhui/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
 [WARNING]: - composer was NOT installed successfully: Could not process data
from the API server (https://galaxy.ansible.com/api/): the JSON object must be
str, not 'bytes'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by jpiron** [comment]
I had the same issue and fixed it by using pip2 to install Ansible:

``` shell
sudo pip2 install --upgrade ansible
```

**Comment by rocha** [comment]
@jpiron what version of python and ansible are you using?

**Comment by jpiron** [comment]
I have both python2 (2.7.12) and python3 (3.5.2) installed. However the one in my path is python2.
Same for pip (pip2 and pip3 installed, version 9.0.1) the default one being pip2.
Ansible version is 2.2.0.0.

**Comment by rocha** [comment]
The error message looks like a python 3 problem:

> `the JSON object must be str, not 'bytes'`

**Comment by chouseknecht** [comment]
The python version is stated to be 3.5.2. Ansible does not yet support python 3. You'll need to switch to python 2.7.

**Comment by metakermit** [comment]
Experiencing this issue as well. It is stated in the [official Ansible docs](http://docs.ansible.com/ansible/python_3_support.html) that:

> Ansible 2.2 features a tech preview of Python 3 support. 

> Technology preview features provide early access to upcoming product innovations, enabling you to test functionality and provide feedback during the development process. 

I would assume from this documentation that reporting issues in Python 3 is desired. If not and Python 3 is not supported at all, it would be good to update the docs to not mislead users.

The problem I am hitting:

```
$ ansible-galaxy install debops.unattended_upgrades --roles-path=./roles
 [WARNING]: - debops.unattended_upgrades was NOT installed successfully: Failed to get data from the API server (https://galaxy.ansible.com/api/): a bytes-
like object is required, not 'str'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```
