### ISSUE TITLE
Unable to import role - get() returned more than one RoleVersion

### ISSUE THREAD

**Issue by lae** [ansible/galaxy-issues#212]
I'm seeing the following in the import log:
```
Starting import 33964: role_name=elasticsearch repo=lae/ansible-role-elasticsearch
Starting import 33964: role_name=elasticsearch repo=lae/ansible-role-elasticsearch
Retrieving Github repo lae/ansible-role-elasticsearch
Retrieving Github repo lae/ansible-role-elasticsearch
Accessing branch: develop
Parsing and validating meta data.
Accessing branch: develop
Parsing and validating meta data.
Parsing galaxy_tags
Parsing platforms
Parsing galaxy_tags
Parsing and validating README
Parsing platforms
Parsing and validating README
Adding repo tags as role versions
Adding repo tags as role versions
An error occurred while importing repo tags: get() returned more than one RoleVersion -- it returned 2!
Import completed
An error occurred while importing repo tags: get() returned more than one RoleVersion -- it returned 2!
Status FAILED : warnings=0 errors=1
Import completed
Status FAILED : warnings=0 errors=2
```
So curently the role isn't being updated. I'm not sure why (and whether the import appearing to be done twice is an issue).

**Comment by lae** [comment]
(and seeing as I've opened an issue - can I get 
fireeye-ops/ansible-role-elasticsearch and 
fireeye-ops/ansible-role-system_ldap removed? they were both moved to under lae/ on github)

**Comment by chouseknecht** [comment]
The two roles are now deleted. Were you not able to delete them from My Roles page?

**Comment by lae** [comment]
Regarding deletion, I've noted multiple issues on this (such as #187). (and yeah, I wasn't able to delete them)

What happened to lae.elasticsearch and lae.system_ldap, however? I did not want those to be deleted.

**Comment by chouseknecht** [comment]
Not sure. I deleted the roles you requested. But there was definitely something wrong in how things were keyed. That's why the import error was happening.

**Comment by lae** [comment]
Alright. I'm guessing that deleting fireeye-ops.elasticsearch ended up deleting lae.elasticsearch (and same for system_ldap). Anyway, I recreated those two roles (albeit losing any counters) so this is resolved for me.
