### ISSUE TITLE
Galaxy not importing roles from github

### ISSUE THREAD

**Issue by MarceloSaied** [ansible/galaxy-issues#213]
Hi, 
I ve created a role , and added to github as ansible-role-iscsi_lnx_1
my user in galaxy is connected to galaxy, yet the role do not apear.
i have googled , and acording on what i found, i tunned the meta main. yml  file
i dont really know how to proceed to publish the role
thanks

**Comment by chouseknecht** [comment]
You have to log into Galaxy using your GitHub account, then go to My Roles and click the slide to the left of the role. If you don't see your role listed, click the refresh button (to the right of the search box).

**Comment by MarceloSaied** [comment]
Hi chouseknecht, Thanks for your answer,
Im loged on with the github account, and used the refresh button in MY ROLES.  Still not appearing :-(
Thanks

https://github.com/MarceloSaied/ansible-role-iscsi_lnx_1

**Comment by chouseknecht** [comment]
The directory structure is incorrect. Everything in iscsi_lnx_1/ should move up a level. Specifically it expects to find meta/main.yml at the top level.

**Comment by MarceloSaied** [comment]
Ha!. thanks for your assistance :-)
