### ISSUE TITLE
add platform Synology

### ISSUE THREAD

**Issue by thomasleveil** [ansible/galaxy-issues#215]
I wrote a role specific to the Synology NAS which comes with their own flavor of Linux.
role : https://galaxy.ansible.com/thomasleveil/ansible-synology-docker-daemon/
It would be nice to add Synology to the list of platforms

You can find more info about Synology DSM [here](https://en.wikipedia.org/wiki/Synology_Inc.#Synology_DiskStation_Manager_.28DSM.29)

**Comment by chouseknecht** [comment]
Added
