### ISSUE TITLE
Import Your Roles from GitHub not working

### ISSUE THREAD

**Issue by kiorky** [ansible/galaxy-issues#216]
from my github username (login: kiorky), the import roles page doesnt update (/roleadd).

**Comment by chouseknecht** [comment]
When you say it does not update, do you mean that your roles do not show up on the list? It will only show public repositories containing a *meta/main.yml* or *ansible/meta.yml*. I also see that you are part of 9 different organizations, so you may need to update the authorized organizations in GitHub.

**Comment by kiorky** [comment]
Yep, nothing shows up, but the most bizarious thing is that the spinner icon doesnt dissappear, some of my orga are very large (plone, zope, collective) and maybe its from there.

The orga im trying to import roles from is [corpusops](https://github.com/corpusops).

**Comment by chouseknecht** [comment]
Have you tried importing roles using the `ansible-galaxy` command line tool? Here's the instructions: http://docs.ansible.com/ansible/galaxy.html#import-a-role

**Comment by kiorky** [comment]
Yep, using the cli worked.
