### ISSUE TITLE
Renamed and renamedGithub Repo blocks import

### ISSUE THREAD

**Issue by hoall** [ansible/galaxy-issues#218]
Hi,

first of all, thank you for your great job. Normally I have no problems at all and that's great :) I really apreciate your work.

At the moment I have a problem with a renamed repository. Your service has now accepted the deletion I guess (at least part of it). The problem is that the name of the repository keeps the same for your site in the end.

I renamed my repository from nginx-proxy to ansible-role-nginx-proxy. So there is a conflict.

Deleting the old one wasn't possible because I renamed first (sorry for that).

I think through reimporting everything it'll fix itself in some time but don't know.

Best regards

**Comment by chouseknecht** [comment]
Overnight we run a background process that rebuilds the search index, removes roles where the GitHub repo is no longer accessible, and updates roles where the repo name has changed.  It looks like your role has been updated:

Checking in the database, the role is associated with the correct repo name:

```
galaxy=> select id, name, github_repo from main_role where github_user = 'hoall';

id   |      name       |         github_repo
-------+-----------------+------------------------------
 13703 | nginx-proxy     | ansible-role-nginx-proxy
 13200 | authorized-keys | ansible-role-authorized-keys
```

And, I was able to kick off an import that ran successfully. Take a look at [your role on Galaxy](https://galaxy.ansible.com/hoall/nginx-proxy/), and see the most recent import.
