### ISSUE TITLE
Paths to share via docker

### ISSUE THREAD

**Issue by goetzk** [ansible/galaxy-issues#219]
While working through the contributing guide docker has warned about the following directories not being shared to docker (while running 'make build'). I don't know if sharing these is required so i haven't attempted a PR but thought I would mention it.

* /Users/username/.galaxy/logs
* /Users/username/.galaxy/config
* /Users/username/GitHub/galaxy

.galaxy/* wasn't created when i saw the message saying it needed to be mounted (i created them so i could share them). if they are required it should probably be mentioned that they need to be created first.

thanks,

**Comment by chouseknecht** [comment]
Presumably you're using Docker for Mac. I have not tested the build process with Docker for Mac. It was put together using Docker Machine. Will work through it at some point, and update accordingly.

**Comment by chouseknecht** [comment]
Running Docker for Mac 1.12.3-beta30.1 (13946). If I look in preferences under File Sharing, I see the following directories are *shared*:

```
/Users
/Volumes
/tmp
/private
```

**Comment by chouseknecht** [comment]
Running `make clean` removes all containers and images related to the galaxy project as well as the ~/.galaxy directory. 

So running the following works successfully without any warnings or errors about unshared paths:

```
$ make clean
$ make build
```

**Comment by goetzk** [comment]
On 28/11/16 05:10, Chris Houseknecht wrote:
> Running Docker for Mac 1.12.3-beta30.1 (13946). If I look in preferences
> under File Sharing, I see the following directories are /shared/:
> 
> |/Users /Volumes /tmp /private |

Interestingly, /Users wasn't shared on mine.

Version 1.12.3 (13776)
Channel: Stable
583d1b8ffe

I'm unsure if its prior configuration on my part (I'm not a big user of
docker) or if it was added at some point.

I'll try again with /Users in the list and see if that succeeds.

thanks,

**Comment by goetzk** [comment]
Thinking about it further, there isn't anything else to do here. /Users wasn't shared, so I was seeing a message about paths that were needed under /Users.
I raised issues with getting the build to work separately so will follow them up there.

Thanks for your help @chouseknecht !
