### ISSUE TITLE
Ignore files from role

### ISSUE THREAD

**Issue by srizzling** [ansible/galaxy-issues#222]
Is there a way I can ignore files being downloaded by the ansible-galaxy client when installing my role. 

I place a vault file in my role, to make the tests run and pass, and I do not want people to download the vault file included to make the tests pass.  

If this isn't part of ansible galaxy, I think it might be useful, maybe via a `.galaxyignore` file maybe?

Thanks,
Sriram

**Comment by danlamanna** [comment]
Agreed, for certain roles I don't want to distribute an exhaustive test suite through Galaxy.

**Comment by srizzling** [comment]
There is a way, which is kind of cheating, but you can add the files you want to ignore to a .gitattributes file in repo and add the flag "export-ignore", an example is here: https://github.com/srizzling/rkt-role/blob/master/.gitattributes.

**Comment by chouseknecht** [comment]
This issue was moved to ansible/galaxy#78
