### ISSUE TITLE
New role on github (org) not appearing

### ISSUE THREAD

**Issue by joshmoore** [ansible/galaxy-issues#225]
I just added github.com/openmicroscopy/ansible-role-basedeps which appeared on galaxy as https://galaxy.ansible.com/openmicroscopy/ansible-role-basedeps/

I would like to update the name of the role, but it is not appearing under "My Roles". What would be the correct sequence to make sure roles are linked to a user's accounts as well? Can they be linked to multiple users' accounts?

_Many thanks_

**Comment by chouseknecht** [comment]
Roles are not actually linked to accounts. To operate on a role in Galaxy, you have to have access to the repo in GitHub, and the repo has to contain a meta/main.yml file. 

It looks as thought the role was sort of added via TravisCI notification. Here's a link to the most recent import: https://galaxy.ansible.com/api/v1/imports/41668/. Based on the error messages, looks like it's missing ``platforms`` in meta/main.yml. Fixing that will make the import succeed.

**Comment by joshmoore** [comment]
@chouseknecht : Thanks. I didn't see any connection between my list of failed builds and 41668; sorry for the newbie failure. Having corrected the platforms issue & clicked on "Refresh Your Repositories" I now have a `joshmoore/ansible-role-basedeps` listed in "My Roles", but none for the org.

**Comment by joshmoore** [comment]
Roles are now present. Whether for a direct intervention or passive hand-holding, thanks for the help!
