### ISSUE TITLE
Init Fails with "the JSON object must be str, not bytes" (Python 3)

### ISSUE THREAD

**Issue by naftulikay** [ansible/galaxy-issues#228]
I am running the following command on Ubuntu 16.04:

```
$ ansible-galaxy init --force example
ERROR! Could not process data from the API server (https://galaxy.ansible.com/api/): the JSON object must be str, not 'bytes'
```

This is a pretty typical Python 2 to 3 problem. I installed `python-pip` and then ran `pip install ansible`, and here's my Ansible and Ansible Galaxy versions:

```
$ ansible --version
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
$ ansible-galaxy --version
ansible-galaxy 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

If I look at the file header for the `ansible-galaxy` command, I see the following:

```
$ head /usr/local/bin/ansible-galaxy
#!/usr/bin/python3

# (c) 2012, Michael DeHaan <michael.dehaan@gmail.com>
#
# This file is part of Ansible
#
# Ansible is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
```

Ansible Galaxy is requesting to run in Python 3 and is somehow failing to be Python 3 compatible. The system Python 3 version is:

```
$ python3 --version
Python 3.5.2
```

The normal system Python version is 2.7, but since Ansible Galaxy is requesting Python 3, that's what it gets. If I force prefix the executable with Python 2.7, it fails saying it can't find Ansible modules and source code.

**Comment by bcoca** [comment]
All ansible scripts are actually a symlink to the base ansible, this is an issue with the installation of Ansible itself, it was pointed at python3 (not just galaxy).

That said, this is still a bug as we strive to be py3.5+ compatible.

**Comment by bcoca** [comment]
closing as this is both in wrong repo and also a dupe https://github.com/ansible/ansible/issues/20012
