### ISSUE TITLE
Inconsistent licensing info in ansible/galaxy repo

### ISSUE THREAD

**Issue by grossws** [ansible/galaxy-issues#233]
https://github.com/ansible/galaxy repo contains `LICENSE` file with Apache License v2 and `license='Proprietary'` + `'License :: Other/Proprietary License',` in `classifiers` in `setup.py`.

**Comment by chouseknecht** [comment]
Fixed.

**Comment by chouseknecht** [comment]
This issue was moved to ansible/galaxy#58
