### ISSUE TITLE
Remove openmicroscopy.haproxy 1.1.1 version

### ISSUE THREAD

**Issue by joshmoore** [ansible/galaxy-issues#235]
See:

 * https://galaxy.ansible.com/openmicroscopy/haproxy/
 * https://github.com/openmicroscopy/ansible-role-haproxy/releases

The 1.1.1 tag has been removed from the openmicroscopy.haproxy repository. Could the build on galaxy be removed as well?

**Comment by chouseknecht** [comment]
This issue was moved to ansible/galaxy#60
