### ISSUE TITLE
Can't reset Ansible Galaxy password through website while logged in

### ISSUE THREAD

**Issue by jeremyn** [ansible/galaxy-issues#237]
I don't see an option to change my password through https://galaxy.ansible.com while I'm logged in. The only account-related options I seem to have are "My Imports", "Manage E-mail", and "Manage Linked Accounts", and none of them let me change my password.

I figured out that I could change my password through the "Forgot password" reset process, but there should be a way to change the password while I'm logged in.

**Comment by chouseknecht** [comment]
This issue was moved to ansible/galaxy#62
