### ISSUE TITLE
Remove roles but still existing

### ISSUE THREAD

**Issue by Ekouyoja** [ansible/galaxy-issues#239]
Hi,

Yesterday i have create a role to test how ansible galaxy work, and when i have understand, i have remove the role from ansible Galxaxy and the Github repo but the role still exist.
How can i remove definetly it ?
Best regards.

**Comment by fabiohbarbosa** [comment]
I have same problem.

**Comment by chouseknecht** [comment]
This issue was moved to ansible/galaxy#64
