### ISSUE TITLE
Hide "karma" in its current form

### ISSUE THREAD

**Issue by gregdek** [ansible/galaxy-issues#24]
It doesn't work very well, and it's not valuable yet. It also begs the question: how do we reward karma? Discounts to Ansiblefest, Tower, etc.? We need to figure out what karma is "good" for, and ensure that the functionality supports that idea.

**Comment by chouseknecht** [comment]
"Karma" is now hidden in the UI.  It is no longer visible on any pages that list users, rank users or provide user details.  The code is commented out.  If we decide at some point how to better define and reward Karma, we can simply uncomment it.

**Comment by gregdek** [comment]
:shipit:

**Comment by gregdek** [comment]
(That's the shipit frog, btw)
