### ISSUE TITLE
No roles found in your public GitHub repositories.

### ISSUE THREAD

**Issue by joshuamkite** [ansible/galaxy-issues#243]
I am trying to publish my first Ansible role. I have signed in to ansible galaxy site using my github account but no matter what I do I get 'No roles found in your public GitHub repositories.' I have been following the documentation at https://galaxy.ansible.com/intro At first I thought the issue might be because I did not have my role as a top-level repository or have 'ansible'  in the repo name but this has made no difference. What am I missing?

**Comment by bouncingsoles** [comment]
I had the same issue.  You need to make sure that you have created a meta directory with a main.yml.  I had a syntax error in my meta so role wouldn't show up.  Use a linter or run ansible-playbook with syntax check to make sure the yaml is OK.

**Comment by chouseknecht** [comment]
This issue was moved to ansible/galaxy#68
