### ISSUE TITLE
tag not being deleted

### ISSUE THREAD

**Issue by steenzout** [ansible/galaxy-issues#251]
I import the role again and again and it doesn't change anything.

e.g. https://galaxy.ansible.com/ansiblebit/oracle-java/ vs https://github.com/ansiblebit/oracle-java/releases

Let me know if there is an option for me to clear the `v` versions out.

thank you!

**Comment by roumano** [comment]
It's a important issue as user are always installing old version of roles...

**Comment by chouseknecht** [comment]
Fixed with this commit. https://github.com/ansible/galaxy/commit/b4d1ca1029bc3b1ab0e4c1c74e74577e3cca42f9

Will push this into production either tonight or tomorrow evening.

**Comment by chouseknecht** [comment]
@steenzout 

You can view the updated role at our QA site: https://galaxy-qa.ansible.com/ansiblebit/oracle-java/

**Comment by chouseknecht** [comment]
This is now in production, and the oracle-java role is up to date, with the correct tags.

**Comment by steenzout** [comment]
@chouseknecht thank you!
