### ISSUE TITLE
supported platforms in metadata

### ISSUE THREAD

**Issue by opichon** [ansible/galaxy-issues#256]
Where can I find the list of supported platforms for a role metadata?

Or more generally a complete description of the metadata syntax.

**Comment by danlamanna** [comment]
This would be a great topic to have documented. Current practice for me is googling and discovering how other roles have things set up.

**Comment by roumano** [comment]
👍 
Can't find from google but this links list of supported platforms for a role metadata 👍 
https://galaxy.ansible.com/api/v1/platforms/
you can adapt the query like this : https://galaxy.ansible.com/api/v1/platforms/?name=EL and the result is a json, so managable by ansible too ...

**Comment by chouseknecht** [comment]
This issue was moved to ansible/galaxy#52
