### ISSUE TITLE
Import removes all instances of ansible in the role name

### ISSUE THREAD

**Issue by thedumbtechguy** [ansible/galaxy-issues#257]
I created a role `ansible-role-ansible-semaphore` hoping to get the name `ansible-semaphore`.
However, galaxy stripped `ansible-role-ansible-` from the name.

I am sure I can change the role name to be what I want, but I don't know if this is a bug or expected behavior.

**Comment by chouseknecht** [comment]
We purposefully strip `ansible` and `role` from the name. Maybe the replace is too greedy, but that's why you have the ability to edit the role name. You can edit, and set it to whatever you like. 

Sounds like editing the role name is working as expected. Closing for now.
