### ISSUE TITLE
Import failures: cannot remove duplicate role

### ISSUE THREAD

**Issue by sbesson** [ansible/galaxy-issues#259]
Partly related the issues reported https://github.com/ansible/galaxy-issues/issues/252

I tried to delete, create and rename the `openmicroscopy.omero-common` role from the base https://github.com/openmicroscopy/ansible-role-omero-common repository. While the role deletion and the creation worked without problem using either `ansible-galaxy` or the Web UI , renaming `openmicroscopy.ansible-role-omero-common` as `openmicroscopy.omero-common` failed with the following stack trace:

```
 Starting import 80728: role_name=ansible-role-omero-common repo=openmicroscopy/ansible-role-omero-common
Accessing branch: master
Parsing and validating meta data.
Setting role name to omero-common
Parsing galaxy_tags
No galaxy_tags found in meta data.
Parsing platforms
Parsing and validating README
Adding repo tags as role versions
Removing old tags
Import completed
Status SUCCESS : warnings=1 errors=0
Error saving role: duplicate key value violates unique constraint "main_role_namespace_36aa1070a7d8dc70_uniq" DETAIL: Key (namespace, name)=(openmicroscopy, omero-common) already exists.
```

This is in agreement with the fact the role is listed in https://galaxy.ansible.com/list#/roles?page=1&page_size=10&autocomplete=omero-common. However, this role does not seem to be mapped to any GH repo, is not listed in my roles and https://galaxy.ansible.com/openmicroscopy/omero-common/ returns 404. Is there a way to remove it from the Galaxy DB or at least rename it so that we can properly reimport the `openmicroscopy.omero-common` role?

/cc @joshmoore @manics

**Comment by joshmoore** [comment]
@chouseknecht : is there any hope of this last one being renamed or shall we come up with a new name?

**Comment by chouseknecht** [comment]
I think this is now the way you want it: https://galaxy.ansible.com/openmicroscopy/omero-common/

Ping me, if it's not. Apologies for not being able to get to this sooner.

**Comment by sbesson** [comment]
@chouseknecht: fantastic, many thanks and no worries about the delay. We'll have a round of internal testing and get back to you if there is any issue.
