### ISSUE TITLE
Ansible Galaxy doesn't see a role from my organization

### ISSUE THREAD

**Issue by wawrzek** [ansible/galaxy-issues#260]
I linked galaxy with my github account and I can see 3 Ansible roles I have once created. Yesterday, Corda organization granted Ansible Galaxy access to it's data:

> An organization owner has approved the following application to access private data in the Corda organization:
>
>  "Ansible Galaxy" from Ansible
>
>Because you are a member of the Corda organization and have already granted this application access to your personal account, Ansible Galaxy can now access Corda organization resources on your behalf.

but I don't see https://github.com/corda/corda-ansible in my roles.  Why?

**Comment by chouseknecht** [comment]
You have to be collaborator on the role's GitHub repo. Galaxy checks the GitHub API to see that the repo is in the list returned by the `user/repos` endpoint.

**Comment by wawrzek** [comment]
@chouseknecht - thanks for your answer. The problem is that I'm (user: wawrzek) a collaborator in corda-ansible role. - I'm checking it Setting->Collaborators (https://github.com/corda/corda-ansible/settings/collaboration)

**Comment by wawrzek** [comment]
I can see it now. No changes applied on my side.
