### ISSUE TITLE
Add fedora 26

### ISSUE THREAD

**Issue by henriklynggaard** [ansible/galaxy-issues#275]
Fedora 26 not accepted during role import

"
Starting import 110354: role_name=gogland repo=henriklynggaard/ansible-role-gogland
Accessing branch: master
Parsing and validating meta data.
Parsing galaxy_tags
Parsing platforms
Invalid platform: Fedora-26 (skipping)
Parsing and validating README
Adding repo tags as role versions
Removing old tags
Import completed
Status FAILED : warnings=0 errors=1
"

**Comment by chouseknecht** [comment]
@henriklynggaard 

Thanks for pointing this out!

Fedora 26 is now available.
