### ISSUE TITLE
Valid platforms: MacOSX + macOS (2016)

### ISSUE THREAD

**Issue by roolo** [ansible/galaxy-issues#276]
In 2016 Apple changed naming to macOS -- https://en.wikipedia.org/wiki/MacOS#macOS . I think, there should be new valid platform in Ansible which would reflect this change.

**Comment by chouseknecht** [comment]
Thanks for pointing this out!

Added 'macOS Sierra'. Going forward we'll use 'macOS' as the platform, and the name (e.g. *Sierra*,  *El Capitan*, etc) as the release. This seems to line up with Apple's web site.
