### ISSUE TITLE
Unable to "remove" role after import

### ISSUE THREAD

**Issue by kso512** [ansible/galaxy-issues#281]
I created some Ansible roles with long names, and I'm in the process of shortening them.  I'm running into "ERROR! Unexpected Exception: No JSON object could be decoded" errors in the command line, and "500 Server Error An error occurred while loading the requested page. Please report this error at Galaxy Issues." errors in the browser.

_____

```
-[2017-09-12|07:06:30]-[kso@golem:~/git/projects/kso512/install-check_mk-server]-
$-> ansible-galaxy setup --list

ID         Source     Repo
---------- ---------- ----------
2077       travis     kso512/ansible-install-check_mk-server
2068       travis     kso512/ansible-install-mpd
2131       travis     kso512/install-check_mk-server

-[2017-09-12|07:06:38]-[kso@golem:~/git/projects/kso512/install-check_mk-server]-
$-> ansible-galaxy setup --remove 2077
ERROR! Unexpected Exception: No JSON object could be decoded
to see the full traceback, use -vvv
```

**Comment by chouseknecht** [comment]
@kso512 

Sorry to hear your running into this. 

I'm not entirely sure of the state of the `setup` command with the `ansilble-galaxy` CLI. A while back we dropped the use of Travis tokens, and the CLI has not been updated. I'll poke at that. 

Also, not sure why you're experiencing 500 errors. I can view your roles on the Galaxy site just fine. Might be worth trying a different browser, or clearing browser cache. 

Are there specific roles that I can delete? Maybe just deleting and re-importing might fix things.

**Comment by kso512** [comment]
@chouseknecht 

Thanks for helping! :)

I was seeing the 500 errors via my browser when looking at the API pages shown in the "-vvv" output.

I think the problem stems from the first role; it was named "ansible-install-check_mk-server" in Github, but Galaxy shortened that to "install-check_mk-server" on first import.  Now I'm trying to rename, and the server is already seeing "install-check_mk-server" as an existing role.

If you can delete any reference to "ansible-install-check_mk-server" and "install-check_mk-server" then I'll try to reimport with the shorter unified name.

Much obliged,
@kso512

**Comment by kso512** [comment]
I was able to get the older version removed, and now only the pure "install-check_mk-server" role exists.  

Thanks!
