### ISSUE TITLE
404 Not found for existing role

### ISSUE THREAD

**Issue by dminca** [ansible/galaxy-issues#285]
Running on ArchLinux `ansible 2.4.0.0`, I got a role deployed on Ansible Galaxy called [vim-ansible-role][1]. As you can see, the role exists and passed the CI test.

But when I try to download it via `ansible-galaxy install -r `[requirements.yml][2] it's throwing **404 Not found**.

#### EXECUTION LOGS

```sh
➜  open-source/containerschiff git:(feat/vim-refactor) ansible-galaxy install -r requirements.yml                
- downloading role 'vim-ansible-role', owned by WizDevOps                                                        
- downloading role from https://github.com/WizDevOps/vim-ansible-role/archive/origin/master.tar.gz               
 [ERROR]: failed to download the file: HTTP Error 404: Not Found                                                 

 [WARNING]: - vim-ansible was NOT installed successfully.                                                        

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.                        
```

I tried re-adding the role on Galaxy, but that didn't work out. I've even tried changing the name, it's a really strange issue.

[1]: https://galaxy.ansible.com/WizDevOps/vim-ansible-role/
[2]: https://github.com/WizDevOps/containerschiff/blob/0843e266c5c7ec4a24f5458c99ba2f9bfecccade/requirements.yml

**Comment by danlamanna** [comment]
While I'm not experiencing this exact issue, I've run into an issue in
recent weeks where a role of mine is 404'ing because it's been renamed
(not by my doing). (The role in question is girder.worker being renamed
to girder.girder-worker).

It's entirely possible this is unrelated, but I thought I would add
another potential data point.

**Comment by chouseknecht** [comment]
The 404 is coming from the path the Galaxy client is using to download the archive file: `https://github.com/WizDevOps/vim-ansible-role/archive/origin/master.tar.gz`

For some reason it contains `origin`. Remove that, and the download works.

**Comment by chouseknecht** [comment]
@dminca 

Change the value of `github_branch` in your meta data https://github.com/WizDevOps/vim-ansible-role/blob/master/meta/main.yml#L8

**Comment by dminca** [comment]
Works now. Wow, this is one of those stupid issues :smile: thank you very much @chouseknecht :tada:
