### ISSUE TITLE
Upgrade django from 1.8 to 1.11

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy-issues#294]
### Action items:

- [ ] Replace `patterns()` with lists of urls.
      > `django.conf.urls.patterns()` is deprecated and will be removed in Django 1.10.

- [ ] Replace string views with callables. 
      > Support for string view arguments to url() is deprecated and will be removed in Django 1.10.

- [ ] Replace usage of `django.utils.importlib`
      > `django.utils.importlib` will be removed in Django 1.9.

More changes to be added.

**Comment by chouseknecht** [comment]
This issue was moved to ansible/galaxy#33
