### ISSUE TITLE
Graphical sort widget confusion

### ISSUE THREAD

**Issue by gregdek** [ansible/galaxy-issues#4]
Original comment from submission: 

When I go to the Explore page on some columns I see an "up/down" arrow, implying I can change the sort direction – which we can't and we don't want to.

We should show a down arrow by the one we are sorting by and not show the arrow on the other one. 

When clicking on the other one, we show the arrow on that one, not the one previously selected. Thus the down arrow points at the column we have selected to sort by.

For widgets that have only one sortable column, a non-clickable down arrow should appear in black.

**Comment by chouseknecht** [comment]
Agree that the sorting indicator thing is confusing. In the develop branch I removed all the sorting indicators and links. There is no more indicator, and the column headers are all the same color (black). We can revisit whether or not users should be able to sort the columns at a later point, if it makes sense.

When I look at the page now it seems much cleaner, and pretty obvious how things are sorted. Everything is in descending order, which coincides with the words 'Top' and 'New'. Take a look. If you feel like it would help to have add a down-arrow next to the column headers, let me know. It's not a problem to add.

**Comment by chouseknecht** [comment]
I also did a bunch of performance tuning on the API endpoints behind Explore, Browse Users and Browse Roles. Far fewer queries are being sent to the database and run times are noticeably faster on my development VM.

**Comment by gregdek** [comment]
No, I'm much happier without them. :shipit:
