### ISSUE TITLE
Document requirements file syntax on https://galaxy.ansible.com/intro

### ISSUE THREAD

**Issue by gregdek** [ansible/galaxy-issues#40]

**Comment by gregdek** [comment]
So to add some color here:
1. There's a specific syntax for specifying a Galaxy role in a role dependency statement: using the Galaxy namepsace format. Is this as simple as anything with "foo.bar" syntax is brought into Galaxy automatically? If that is the case, we should document that somewhere. :) (Probably in the Ansible documentation itself rather than in the Intro page; Intro should just point to proper role docs.)
2. In version 2, we will have a "path=" syntax option for any role that will support Github and other download mechanisms. This is also undocumented. (Should probably be tagged as "beta" in the documentation until release of 2.0 is final.)

**Comment by chouseknecht** [comment]
- Revised the About page to reflect simpler role ratings. 
- Added a bunch more info and examples for dependencies. There is also a link to http://docs.ansible.com/ansible/playbooks_roles.html?#role-dependencies for more info.
- Fixed a few typos.

Not sure what to do about #2. Agree that it should be documented. Have not had time to research how things actually work in v2.

**Comment by gregdek** [comment]
This looks good to me. We'll defer on the v2 stuff for now.

**Comment by gregdek** [comment]
Shipped!
