### ISSUE TITLE
site is indexed oddly in google

### ISSUE THREAD

**Issue by wenottingham** [ansible/galaxy-issues#47]
![galaxy](https://cloud.githubusercontent.com/assets/5208768/9207233/531405b4-403a-11e5-93a7-af5f414b57ae.png)

See above.

**Comment by gregdek** [comment]
@wenottingham do you still see this? We can't reproduce it. Could have been "accidentally" fixed in 1.0 release.

**Comment by chouseknecht** [comment]
![galaxy google search](https://cloud.githubusercontent.com/assets/1282865/9444471/00201dc8-4a55-11e5-8bd2-d5c9d667f1d0.png)

**Comment by wenottingham** [comment]
Nope, WFM now.
