### ISSUE TITLE
Make "ansible-galaxy install" idempotent

### ISSUE THREAD

**Issue by dixhuit** [ansible/galaxy-issues#49]
Currently if you run `ansible-galaxy install` more than once it will fail. Adding the `--force` option gets around this but is inefficient in that it will re-download all required roles, regardless of whether it needed to.

Given that this is Ansible, I'm surprised that the command works in this way. I'd prefer to see `ansible-galaxy install` not fail on more than one run but instead just report that all is in order or update roles where required (just like Ansible's `git` module).

I'm really pleased to hear that Galaxy is finally getting some love :)

**Comment by geerlingguy** [comment]
++

**Comment by rsvalerio** [comment]
:+1:

**Comment by aussielunix** [comment]
Just took a quick look at this, in Ansible 2 (but have zero python experience) and found a simple fix for now.
It still is less than optimal in that it will download the role before deciding it is already installed but it is better than running with `--ignore-errors` all the time.
https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/role.py#L220-L221

```
diff --git a/ansible2/lib/ansible/galaxy/role.py b/ansible2/lib/ansible/galaxy/role.py
index ea6debb..1633a8f 100644
--- a/ansible2/lib/ansible/galaxy/role.py
+++ b/ansible2/lib/ansible/galaxy/role.py
@@ -217,8 +217,8 @@ class GalaxyRole(object):
                         display.error("the specified roles path exists and is not a directory.")
                         return False
                     elif not getattr(self.options, "force", False):
-                        display.error("the specified role %s appears to already exist. Use --force to replace it." % self.name)
-                        return False
+                        display.display("**the specified role %s appears to already exist. Use --force to replace it.**" % self.name)
+                        return True
                     else:
                         # using --force, remove the old path
                         if not self.remove():
```

**Comment by staylorx** [comment]
+1

**Comment by lhoss** [comment]
+1

**Comment by yeroc** [comment]
+1

**Comment by cjw296** [comment]
+1

**Comment by nhooey** [comment]
Please use the GitHub ["reaction" feature](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) on the original comment instead of generating messages that everyone will get notified for.

**Comment by cjw296** [comment]
Oh, I do both just to make sure ;-)

**Comment by chouseknecht** [comment]
Please comment on https://github.com/ansible/proposals/blob/master/auto-install-roles.md

**Comment by cjw296** [comment]
@chouseknecht - disappointed to see this closed. This feature request was simple and clear; paraphrasing: make ansible-galaxy behave like pip install. The proposal you link to muddies all this with none of the options making much sense to me.

**Comment by cjw296** [comment]
@chouseknecht - furthermore, please can you explain how to comment on that proposal? I see no options or UI clues as to how to do so...

**Comment by tima** [comment]
@cjw296: @chouseknecht posted the wrong link to comment on that proposal. The autoinstall proposal was submitted before we shifted the proposal review process to issues. Apologies for the confusion. Use this one: https://github.com/ansible/proposals/issues/7 to comment

I disagree with your characterization that this is feature request is simple. For a sample of the challenges look at the existing comments on the proposal linked above and other discussions like this one: https://github.com/ansible/ansible/issues/6466#issuecomment-234387668

**Comment by cjw296** [comment]
@tima - the feature request was simple, the implementation potentially less so.

We're basically talking about installing dependent library software. In the Python world, we already have pip/virtualenv and conda as comparable examples, both of which support "make my current environment like this specification which comes from a file" in an idempotent way. `requirements.yml` gives us the  specification, now we just need the idempotent install, rather than requiring the --force hack.

Autoinstall, for me, would be akin to python magically downloading and installing a package as part of an import statement. Sure, you can implement one of the import hooks to do it, but most people would make decidedly unhappy faces in your general direction if you did.

**Comment by cjw296** [comment]
@chouseknecht - since @willthames said the proposal you referred to is completed unrelated, please can you re-open this issue?
