### ISSUE TITLE
Sort by high scores first

### ISSUE THREAD

**Issue by gregdek** [ansible/galaxy-issues#5]
Nothing urgent, just a suggestion for the Galaxy website:

The default sort order for Average Score should be high scores first. I keep having to check Reverse Order to see the good stuff, which is just silly.

**Comment by chouseknecht** [comment]
Fixed in develop branch.

**Comment by gregdek** [comment]
Hmm, interesting bug:
1. Click on Explore. (Only seems to appear through this code path.)
2. Under Top Roles, click "View More". You're taken to the "Average Score" view of the roles page, with the "Reverse Order" box checked.
3. Try to uncheck the "Reverse Order" box. You can't!
4. Change from "Average Score" as the sort criteria to "Owner Name". Reverse Order box gets unchecked.
5. Click the "Reverse Order" box -- you're taken back to the reverse-sorted community score!

**Comment by chouseknecht** [comment]
I was able to reproduce and fix this. Nice catch!

**Comment by gregdek** [comment]
Don't tell anyone else I'm good at QA. ;)

:shipit:
