### ISSUE TITLE
Add "macOS" as a platform option

### ISSUE THREAD

**Issue by dixhuit** [ansible/galaxy-issues#51]
...because right now the closest we've got to work with is possibly "GenericUNIX" which doesn't really cut it.

**Comment by jrenggli** [comment]
+1

**Comment by bborysenko** [comment]
:+1:

**Comment by chouseknecht** [comment]
Done

**Comment by dixhuit** [comment]
Apple have rebranded the OS since I originally opened this issue. I guess the platform option we now need is "macOS"?

**Comment by dixhuit** [comment]
@chouseknecht Can you confirm what exactly is "done"? Have you added "Mac OS" (now incorrect) or "macOS"?
