### ISSUE TITLE
Adding a role called "Ansible" results in un-named role

### ISSUE THREAD

**Issue by aussielunix** [ansible/galaxy-issues#53]
When I browse to  https://galaxy.ansible.com/accounts/profile/#/
And I click `Add A Role` at the top of the page
And I entrer my username - `aussielunix`
And I enter a Github Repository Name of `ansible-ansible`
And I leave Alternate Name `blank`
OR I enter an Alternate Name that still contains `ansible`
Then my role is add but without a role name

![galaxy1](https://cloud.githubusercontent.com/assets/261833/9427055/9b8a5f2c-49aa-11e5-8c11-be92f4d322d1.jpg)

If I do this process again but instead enter an Alternate Name of `ansible-ansible-ansible` IT WORKS !

![galaxy2](https://cloud.githubusercontent.com/assets/261833/9427057/bafbae38-49aa-11e5-81f1-bb6e987e5924.jpg)

**Comment by geerlingguy** [comment]
See related: https://github.com/ansible/ansible/issues/11556

**Comment by gregdek** [comment]
Yep. We got it. See ansible/ansible#11556 for details.

**Comment by aussielunix** [comment]
Thanks @gregdek. Just for some context, I wrote this role for making sure my CI slaves have ansible installed.

**Comment by chouseknecht** [comment]
- 'ansible' and 'Ansible' are now accepted as role names using either Github repository name or Altername Name value. 
- 'ansible-role-ansible' results in a role name of 'ansible'.
- 'ansible-ansible-ansible..' and 'ansible-role' is rejected. If all you want is a role name of 'ansible', then use Alternate Name 'ansible'

Here's a screen shot of the revised page which hopefully explains how role naming works:

![addrolepage](https://cloud.githubusercontent.com/assets/1282865/10743729/63e038b0-7c0b-11e5-8b88-3faf1aefeaab.png)

And, if your role name is rejected, we now have better error handling:

![roleadderror](https://cloud.githubusercontent.com/assets/1282865/10742879/f513de6e-7c05-11e5-9c68-568655893fff.png)

**Comment by jlmitch5** [comment]
verified that you can add a role that's just named "ansible" and set the alternate name to "ansible"

**Comment by jlmitch5** [comment]
verified name and altername "ansible-role-foo" results in name being "foo"

**Comment by jlmitch5** [comment]
verified useful error message in trying to type alternate name ansible-role.

**Comment by jlmitch5** [comment]
verified useful error message in trying to type alternate name ansible-ansible.

also verified ansible-ansible-role-foo results in name "foo"

**Comment by jlmitch5** [comment]
:+1:

**Comment by geerlingguy** [comment]
So, uh... my existing role is still showing up as "" (blank, no title) in listings and on its own page—what can I do to make it appear? See: https://galaxy.ansible.com/detail#/role/1007 (on GitHub: https://github.com/geerlingguy/ansible-role-ansible).

**Comment by jlmitch5** [comment]
hey @geerlingguy, I was helping out on the QA front and validating some stuff that's going to make it into the next Galaxy release...these were verification notes from testing on our staged instance of Galaxy.  When 1.1.1 lands, this should be fixed.

Also, I apologize for the slew of emails everyone in this thread received.  When I was assigned this task, I didn't take that into account before sending a bunch of comments.  My bad!

**Comment by geerlingguy** [comment]
@jlmitch5 - Oh, perfect! And keep up the incredibly-awesome work—Galaxy has already improved about 20x in the past month, after having almost a year with barely an update :)
