### ISSUE TITLE
GitHub group support

### ISSUE THREAD

**Issue by groggemans** [ansible/galaxy-issues#59]
As of January first 2016 only GitHub authentication is supported. This means you can no longer have a galaxy account for uploading roles of a GitHub group. (Or you have to upload them under a different name -> not wanted!) 

There should be an option to upload roles from a GitHub group, under the groups name, from a personal account. (Just like you manage groups from your personal account on GitHub and Travis)

**Comment by MiLk** [comment]
:+1: 

We manage a lot of roles under an organization: https://github.com/AerisCloud https://galaxy.ansible.com/list#/users/11183
And it should not be linked to only one github account.

**Comment by gregdek** [comment]
Good feedback; makes sense. Also impacts how we do namespacing ultimately.

**Comment by srgvg** [comment]
:+1: see also my comment on #64

**Comment by gregdek** [comment]
Going to start scoping this now. Stay tuned.

**Comment by MiLk** [comment]
:+1:

**Comment by MiLk** [comment]
I'm happy with what is currently proposed on https://galaxy-qa.ansible.com/

I can import all the roles from my organization while being connected with my personal GH account.

**Comment by groggemans** [comment]
Looks good to me too, nice work!

**Comment by gregdek** [comment]
Thanks for looking at it @MiLk and @groggemans -- we'll probably close this when we launch 2.0 officially (which will probably be after the holidays).

**Comment by groggemans** [comment]
As 2.0 is launched this issue is resolved. Thank you!
