### ISSUE TITLE
Re-import shows "Failed to find a README.md" but the README.md exists.

### ISSUE THREAD

**Issue by ypid** [ansible/galaxy-issues#65]
What I did: I tried to re-import some of my roles yesterday but I got the message:

> FAILED:
> Failed to find a README.md. All role repositories must include a README.md. Please refer to the 'Getting Started' documentation regarding role requirements. Once the issue has been corrected in the repsotitory, you can retry the import.

(Note the typo: repsotitory)

So I tried to re-import all other of my roles to see if there is some hint. Unfortunately I could not find any correlation.

Roles that can be re-imported:
- https://galaxy.ansible.com/list#/roles/2807
- https://galaxy.ansible.com/list#/roles/2980
- https://galaxy.ansible.com/list#/roles/3015
- https://galaxy.ansible.com/list#/roles/3042
- https://galaxy.ansible.com/list#/roles/3314
- https://galaxy.ansible.com/list#/roles/3315
- https://galaxy.ansible.com/list#/roles/3778
- https://galaxy.ansible.com/list#/roles/3980
- https://galaxy.ansible.com/list#/roles/4109
- https://galaxy.ansible.com/list#/roles/4557
- https://galaxy.ansible.com/list#/roles/4559
- https://galaxy.ansible.com/list#/roles/4633
- https://galaxy.ansible.com/list#/roles/4649
- https://galaxy.ansible.com/list#/roles/4668
- https://galaxy.ansible.com/list#/roles/4752

Roles that can not be re-imported (due to the noted error):
- https://galaxy.ansible.com/list#/roles/2758
- https://galaxy.ansible.com/list#/roles/4054
- https://galaxy.ansible.com/list#/roles/4058
- https://galaxy.ansible.com/list#/roles/4113
- https://galaxy.ansible.com/list#/roles/4114
- https://galaxy.ansible.com/list#/roles/4558
- https://galaxy.ansible.com/list#/roles/4749

BTW: All the roles do include a `README.md` and some of the roles which can not be re-imported have not been changed for a while …

Reopened here. Old issue: https://github.com/ansible/ansible/issues/9269

**Comment by gregdek** [comment]
Great feedback. Thanks for moving the bug over for us.

**Comment by mauricios** [comment]
I'm having the same issue with my roles, all of them have failed with the the same error, even the ones previously working and unchanged for a while.

**Comment by dguerri** [comment]
Same issue here. I can reimport 0 out of 10 roles I have :(

**Comment by gregdek** [comment]
We know the issue. It's a unicode bug in the importer. Should be fixed next release (within the next week or two); in the meantime, the temporary workaround is to strip unicode characters from README.md, import, and then put the unicode characters back in the README.

**Comment by Mayeu** [comment]
Any news on the correction of this bug?

**Comment by gregdek** [comment]
Should be in the next release of Galaxy, which should happen in the next
two weeks.

On Thu, Oct 1, 2015 at 3:58 AM, Mayeu (Cast) notifications@github.com
wrote:

> Any news on the correction of this bug?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/galaxy-issues/issues/65#issuecomment-144649299
> .

## 

Greg DeKoenigsberg
Ansible Community Guy

Find out why SD Times named Ansible
their #1 Company to Watch in 2015:
http://sdtimes.com/companies-watch-2015/

**Comment by ypid** [comment]
Issue seems be resolved. At least all my roles can be imported now :+1:
