### ISSUE TITLE
Cannot name role 'ansible'

### ISSUE THREAD

**Issue by tersmitten** [ansible/galaxy-issues#69]
I created a role that installs Ansible. It is named `ansible`. It looks like `ansible` is a reserved word or something because it's not displayed in the UI:
- https://galaxy.ansible.com/list#/roles/4397
- https://galaxy.ansible.com/accounts/profile/#/

**Comment by aussielunix** [comment]
Duplicate of https://github.com/ansible/galaxy-issues/issues/53

**Comment by geerlingguy** [comment]
See also https://github.com/ansible/ansible/issues/11556

**Comment by gregdek** [comment]
OK, closing this as duplicate of #53. We'll get it sorted out. :)
