### ISSUE TITLE
Galaxy does not let me to add my role to it

### ISSUE THREAD

**Issue by ghost** [ansible/galaxy-issues#71]
Hey, when i try to add my role (https://github.com/aydintd/percona_mysql)

It does not let me to add it and throwing and weird exception :

FAILED:
Failed to find a README.md. All role repositories must include a README.md. Please refer to the 'Getting Started' documentation regarding role requirements. Once the issue has been corrected in the repsotitory, you can retry the import.    

I have a README.md file in my role and i don't think that i did something wrong

**Comment by gregdek** [comment]
Known issue with unicode in README files; slated to be fixed in upcoming release.

Workaround now is to remove unicode.

**Comment by ghost** [comment]
Thanks for notifying me @gregdek , There was an "ı" character in my name in the README.md file so I changed "ı" turkish letter to "i" after that i could deployed my role to galaxy successfully.

People should notice that galaxy does not like non-ascii letters in README file for now.

I'm closing the issue, thanks.
