### ISSUE TITLE
Ansible Galaxy username syncing with Github

### ISSUE THREAD

**Issue by kmf** [ansible/galaxy-issues#72]
Will usernames be synced from Github to Galaxy, when the switch happens in January,
reason I'm asking is that my github username is 3 characters and it seems that Galaxy only supports 4 characters and up.

**Comment by kmf** [comment]
Updates?

**Comment by gregdek** [comment]
None as yet. Don't worry; we're still considering our Github approach. If we need to push it out, we will, and we'll make sure we have an answer for this issue.

**Comment by chouseknecht** [comment]
Min length changed from 4 to 3.
