### ISSUE TITLE
Add Sign In menu option

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-issues#75]
When on Browse Roles, Browse Users or any interior page there should be a menu option for authenticating. Currently the only option is to go back to the home page. 

Upon successful authentication redirect user back to the page (with all the same parameters) where the Sign In button was clicked.

**Comment by chouseknecht** [comment]
Changed pushed to QA and ready for testing.

**Comment by gregdek** [comment]
Some improvements yet, will be filed in a new rfe, but for this one, :shipit:

**Comment by robynbergeron** [comment]
I can confirm this has been added and works in the ways expected above!

**Comment by gregdek** [comment]
Shipped!
