### ISSUE TITLE
Why ansible-galaxy install option can't read roles dependencies from playbook file?

### ISSUE THREAD

**Issue by rsvalerio** [ansible/galaxy-issues#78]
I mean, if i have that in my playbook.yml

```
  roles:
    - { role: pm.pacote, tags: pacote, version: 1.0.3 }
    - { role: pm.rede, tags: rede, version: 2.0.3 }
    - { role: pm.localizacao, tags: localizacao, version: 0.0.1 }
    - { role: pm.ntp, tags: ntp }
```

Then, to install depencies:

```
ansible-galaxy install -r playbook.yml
```

Or even better, assuming playbook.yml as default playbook file name

```
ansible-galaxy install
```

This way, we'll have better information about role version used in playbook and a trick/easy way to install dependencies.

**Comment by fwisehc** [comment]
+1 

it should also be able to install role dependencies from the `dependencies` variable in meta/main.yml.  

```
> cd my-role
> ansible-galaxy install
... reading dependencies from meta/main.yml 
... downloading dependencies
... downloading git+ssh://git@github.com:myorg/rolename
... downloading galaxy user.rolename
```

or 

```
ansible-galaxy install -r ./my-role/
... detected role my-role
... installing dependencies from ./my-role/meta/main.yml
... etc
```

otherwise we have to maintain duplicate information in the "meta/main.yml dependencies" variable and requirements.yml

**Comment by chouseknecht** [comment]
There is a proposal for changing how roles are installed here: https://github.com/ansible/proposals/blob/master/auto-install-roles.md. Please direct comments there.

**Comment by marcstreeter** [comment]
How do we direct comments to that?
