### ISSUE TITLE
Author field in meta.yml seems to be ignored.

### ISSUE THREAD

**Issue by gregdek** [ansible/galaxy-issues#79]
When I upload a role, every author field in the Galaxy UI itself seems to be populated by the User ID (Github ID in this case) of the user who uploaded the role.

The actual field in meta/main.yml seems to be ignored.

Steps to replicate:
1. Fork a Github role. In my case, I forked Jeff Geerling's Munin role:
   https://github.com/gregdek/ansible-role-munin
2. Log in as whomever.
3. Put "some-random-name" in the author: field of meta/main.yml, so that the "some-random-name" is not the same as your login.
4. Upload the role.
5. Search roles by your login. Your role is found!
6. Search roles by "some-random-name" specified in meta/main.yml. Nothing found!

I think this means that we're asking people to populate a field that is ignored. We should figure out what behavior we actually want there.

**Comment by gregdek** [comment]
So ultimately the decision is to continue to ignore the Author: field, but to file a PR against Ansible itself to pull the Author: field out of the required metadata here. Pushing to consideration in 1.2 (but really this should be filed against ansible/ansible first.)

**Comment by chouseknecht** [comment]
This seems to be fine the way it is.
