### ISSUE TITLE
More clarity in Reviews tab

### ISSUE THREAD

**Issue by robynbergeron** [ansible/galaxy-issues#80]
I think an additional point of clarity could be that if you are browsing a role that doesn't have a rating (though this is super low priority IMO):
-  If you click on the Reviews tab, and the role has no reviews, it says "no ratings found" -- maybe this could simply be "no ratings or reviews found"? Just so people aren't wondering which is actually supposed to be provided?
- I think that people may naturally expect / wander to the Reviews page to add a review or rating -- and thus having some sort of "add your rating" button would be logical.

**Comment by chouseknecht** [comment]
We no longer have ratings/reviews.
