### ISSUE TITLE
"Sign in" option should appear in the grey bar on home page of galaxy 

### ISSUE THREAD

**Issue by robynbergeron** [ansible/galaxy-issues#82]
This is related to #75.

Now that the "sign in" link in the grey bar is available for each option (explore, browse roles, browse users)  and redirects properly -- it seems as though the front page of Galaxy might want to have a unified look with the rest of the pages and also provide a sign-in button.

I realize that the "log in with github!" and so forth is RIGHT BELOW -- but I think some people may just have a habit of always wanting to click up there or are used to seeing it there, and I think it would provide some visual continuity for people as well (less distraction when moving around) if they're not authenticated.

**Comment by chouseknecht** [comment]
Fixed.

**Comment by jlmitch5** [comment]
I agree this is an improvement to the UX, and I have verified that sign in/authed user shows up in the top right of the grey bar.  I've also verified that logging in works from clicking sign in, or from the "login w github" button.  :+1:
