### ISSUE TITLE
Install the roles:  `$ ansible-galaxy -r install_roles.yml` - wrong example

### ISSUE THREAD

**Issue by frncmx** [ansible/galaxy-issues#85]
[Download-advanced section](https://galaxy.ansible.com/intro#download-advanced) contains wrong ansible-galaxy command on Galaxy's Intro page.

`$ ansible-galaxy -r install_roles.yml # wrong`

`$ ansible-galaxy install -r install_roles.yml # OK`

**Comment by gregdek** [comment]
Closing as dup of #86 -- thanks!
