### ISSUE TITLE
https://galaxy.ansible.com/intro `ansible-galaxy -r roles.txt` incorrect example

### ISSUE THREAD

**Issue by mbylstra** [ansible/galaxy-issues#86]
The example given is `ansible-galaxy -r roles.txt`, but this fails in Ansible 9.x.
It should be `ansible-galaxy install -r roles.txt`

**Comment by chouseknecht** [comment]
Fixed.

**Comment by jlmitch5** [comment]
Verified docs have been updated to include the correct command.  :+1:
