### ISSUE TITLE
Default branch is not necessarily master

### ISSUE THREAD

**Issue by nervo** [ansible/galaxy-issues#87]
When trying to install a role with ansible-galaxy without specifying version, master branch is automatically  checked.
In our roles (https://github.com/ElaoInfra), to avoid versions nightmares, and force their specifications, we have set the default branch to "1.0" instead of "master".

It could be sweet if ansible galaxy could check this default branch before trying master

**Comment by MiLk** [comment]
Have you tried with a more recent version of git?
I remember having the same issue in the past, and it was related to the version of git.
http://stackoverflow.com/a/32503667

**Comment by chouseknecht** [comment]
You can set the default branch in meta/main.yml. In this case, set `github_branch: "1.0"`.
