### ISSUE TITLE
Role data should show "last modified" instead of "created"

### ISSUE THREAD

**Issue by gregdek** [ansible/galaxy-issues#88]
We can try to show both, but if we can't, we should show modified instead of created because it's more useful data. Or maybe we show modified in the list views and both modified and created in the detail views.

**Comment by chouseknecht** [comment]
Added last modified date.

**Comment by jlmitch5** [comment]
Verified that the date shows up on the roles list page (the one with all the blocks).  That data isn't on a role detail page (ie: https://galaxy-qa.ansible.com/detail#/role/6) that I can see.  Should it be @chouseknecht?
