### ISSUE TITLE
Fix broken role links

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-issues#89]
In release 1.1 we changed the URL structure for accessing role details. It went from list#/roles/:role_id to detail#/role/:role_id. 

This change breaks links to Galaxy roles. If someone stuck a link to a Galaxy role in a blog post, for example, that link is now broken.

**Comment by chouseknecht** [comment]
Fixed and pushed into production.

I didn't realize changing the URL structure would break lots of links. Turns out many people do something like the following to add a badge to their role github repo: 

[![Galaxy](http://img.shields.io/badge/galaxy-cchurch.win--ec2-blue.svg)](https://galaxy.ansible.com/list#/roles/4344)

Breaking all badges would be really bad. :-(

**Comment by tersmitten** [comment]
Thanks @chouseknecht

**Comment by cchurch** [comment]
@chouseknecht :clap:
