### ISSUE TITLE
Platforms: Arch Linux

### ISSUE THREAD

**Issue by coxley** [ansible/galaxy-issues#93]
Arch Linux should have a platform the same as Ubuntu, Debian, RHEL, and so on.

**Comment by chouseknecht** [comment]
@coxley not familiar with Arch Linux versioning. Looking that the [releases page](https://www.archlinux.org/releng/releases/). Should I use the release date as the version or the kernel version?

Thanks!

**Comment by coxley** [comment]
@chouseknecht That _might_ be a decent guideline but those releases are the install image releases. In practice Arch is rolling release and has no version. One may choose to freeze their kernel version for hw compat reasons while upgrading other things, etc.

Everything is more or less upstream as far as the system packages go.

**Comment by chouseknecht** [comment]
Forgot all about this. Apologies. Added `ArchLinux` as a platform without any specific versions.
