### ISSUE TITLE
Clarify: ansible-galaxy install requires root privileges by default

### ISSUE THREAD

**Issue by brianshumate** [ansible/galaxy-issues#94]
The current [Download Roles](https://galaxy.ansible.com/intro#download) documentation implies that a non-root user can simply do the following:

```
ansible-galaxy install username.rolename
```

Given that the default `roles_path` value is `/etc/ansible/roles`, what occurs instead is write failure due to lack of permissions:

```
ansible-galaxy install username.rolename
- downloading role 'username.rolename', owned by username
- downloading role from https://github.com/username/rolename/archive/v1.0.0.tar.gz
- extracting username.rolename to /etc/ansible/roles/username.rolename
- error: you do not have permission to modify files in /etc/ansible/roles/username.rolename
- username.rolename was NOT installed successfully.
- you can use --ignore-errors to skip failed roles.
```

Perhaps the addition of a note prior to referencing the install command about where the role will be extracted, and the need for root privileges (e.g. prefix command with `sudo` or similar) would help users avoid this issue. This seems to be a common pitfall for folks using my Galaxy published roles, and leaves a bad first impression with respect to ease of use.

Bonus points for mentioning or linking to `ansible.cfg` and the `roles_path` setting in there with a note that the user can set it to a path that they actually have write permissions on.

Cheers!

**Comment by chouseknecht** [comment]
Added.
