### ISSUE TITLE
Role import - alternate name

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy-issues#95]
We have a user that would like the alternate name to NOT be tampered with by the import process. The thought is that the alternate name comes with an expectation that it will be the final name. But that doesn't always prove to be the case. If the user tries to do something like 'ansible-deps', the 'ansible-' piece is getting dropped.

**Comment by MiLk** [comment]
I agree that we should be able to choose a different name or to drop the `ansible-` part.
For example, with the old version we had the `ansible-zeromq` repo for the `zeromq` role (https://galaxy-qa.ansible.com/detail#/role/4048), but now, we have `ansible-zookeeper` for `ansible-zookeeper` (https://galaxy-qa.ansible.com/detail#/role/6394).
And we would like to name the role `zookeeper` and not `ansible-zookeeper`, without changing anything to our GH repo.

**Comment by gregdek** [comment]
Perhaps the one case we should re-enable here is the removal of a leading "ansible-" for a role name, since that seems to be the case that's biting most folks. I don't like the idea of maintaining separate role name mappings for the sake of "prettiness", but if enough people overrule me, we should consider it. :)

**Comment by MiLk** [comment]
I'm ok to not have a total freedom over the alternate name.
But if you look at most of the roles on Github, they are all prefixed by `ansible-`.

Out of the 10 most prolific users listed on https://galaxy.ansible.com/explore
9 are prefixing their roles with `ansible-`:
- https://github.com/debops
- https://github.com/Oefenweb
- https://github.com/kbrebanov?tab=repositories
- https://github.com/andrewrothstein?tab=repositories
- https://github.com/ElaoInfra
- https://github.com/azavea
- https://github.com/mrlesmithjr?tab=repositories
- https://github.com/geerlingguy?tab=repositories
- https://github.com/telusdigital

And none of them have the `ansible-` prefix on Galaxy.

**Comment by gregdek** [comment]
Tough to argue with data. It is a convention that we've already established, and it appears that most people are following it. Thanks for the homework @MiLk. We'll take a closer look.

**Comment by chouseknecht** [comment]
The user now has full control of the alternate name. This is true since Galaxy 2.0.
