### ISSUE TITLE
Token authentication for API / refresh roles though API

### ISSUE THREAD

**Issue by benwebber** [ansible/galaxy-issues#98]
It would be useful to refresh roles automatically as part of a release process, or alternatively as a GitHub webhook.

I discovered that you can refresh roles with a simple `GET` if you have already authenticated:

```
GET /accounts/role/refresh/{id}
```

It would be nice if this was possible through the API as well. Perhaps something along the lines of:

```
GET /api/v1/roles/{id}/refresh
```

The API would require some sort of token-based authentication. Here are two example mechanisms:
1. Leverage GitHub Oauth
   1. The user generates an Oauth access token on GitHub.
   2. The user passes the token as part of their Galaxy request.
   3. Galaxy authenticates on behalf of the user transparently and does not store the token.
2. Leverage Django authentication
   
   Do not use GitHub Oauth. Use an existing Django authentication provider to provide an API-specific authentication mechanism.

**Comment by chouseknecht** [comment]
You can import roles via Travis notification. See https://galaxy.ansible.com/intro#travis.

Roles can also be imported via the API see [galaxy-import-role](https://galaxy.ansible.com/chouseknecht/galaxy-import-role/) for an example.

**Comment by benwebber** [comment]
Thanks! I've been using the Travis integration since you rolled it out. I like the standalone example you put together.
